---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tinyauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TINYAUTH_SECRET: "{{ .TINYAUTH_SECRET }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: "{{ .TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: "{{ .TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET }}"
  dataFrom:
    - extract:
        key: tinyauth
