---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: privileged
---
# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: allow-same-namespace
#   namespace: cert-manager
# spec:
#   endpointSelector: {}
#   ingress:
#     - fromEndpoints:
#         - {}