apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-values
  namespace: immich
data:
  values.yaml: |

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              pullPolicy: IfNotPresent
              tag: v2.0.1
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true

          env:
            REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
            IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          enabled: true
          existingClaim: immich-library-pvc

    valkey:
      enabled: true

      persistence:
        data:
          enabled: true
          existingClaim: immich-valkey-pvc

    server:
      enabled: true
      ingress:
        main:
          enabled: true
          className: traefik
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: immich.sluxcloud.com
              paths:
                - path: "/"
                  pathType: Prefix

    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                pullPolicy: IfNotPresent
              env:
                TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          existingClaim: immich-ml-pvc
          accessMode: ReadWriteMany