apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
stringData:
    values.yaml: ENC[AES256_GCM,data:SkxUkwyhP28Q3OmAi3bohjOLk+B3toKefx9H2Zo/7Cun37zXBD0TLxtwiDCHdQ6tt5PnI5CkV8LOaKk5E2MEIU4Lia2B3eOQ2MCubmPdiIVnHxGozSiYFNFXu4tDCbkU1wYaBiYT+gccyIn+mGubwe4Yxcraq3MTQx0DMxvrL78Sil3DwsQ3xtOb7JpclVOTBSj9RFQLmidsdksI+nICQVGCNMMNGhBR/1roYOz8MXXyQvmUAZuSDdcHFJOlgPGjW89l+AVuazs8aJFTF8Gx/lyFWfnvLobfwMVbQfkB8YfHrGvoasMYeEs=,iv:l1kXYDgwMfsic3HW5zy73gCMUOFxuuLVHXckQ19AdCQ=,tag:DgtVPOQ1SK5ZwH91rIgfvg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS3FLSE1sTUVVVDRBLzF1
            aDZCN2cwTm1DMzcwT3dEYjVicytMZllFekhvCk1oOEdSTTVReDVSbTd6bHBwcUJw
            YVBKVjVMc1AyeHY4RksvVGltSnBPYlUKLS0tIGRjdWwvbFF6K0NiTENjb04wSHY3
            aVQyUWttbTA1YXNHTXhJM0xaT21WWU0KaeBocjTuL0BiVbgvSKxsiX+jkm80iEIQ
            8o4P/lnzfF+06k50ob9kdIXoZqoRAIuzrVbqvWUGs6RVwVV5ud7Vtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T23:35:02Z"
    mac: ENC[AES256_GCM,data:rxnD3HaRnefyCVGD/fu/ZJg4sIK6sdwMlloWt+pF+OOCLRkmEt/+Z+B4ox0L0pcfWztNpGn5UkDqKu+1xXZwDEWRD2ZPP4EUkA7DnE2RNpd31PZ24gEyBZg5+6HZJJBeFEulybb8sWdDH7lfXN7E7DHkVaRd6G0YE9JrOXi40gc=,iv:QL6j6MMm6efj74hVZhVUXRaR7UAlGnuSTJZ2h3FzReU=,tag:/T3HEdFtx3cAT66wL4YlZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
