apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
stringData:
    values.yaml: ENC[AES256_GCM,data:9hMG014Bg6di74gIq91qbVvs6SmAn+F06DMwBp9+DZT0fEbeyAFx90+yScm//fz0fAcPSQSuxGo6Qep4Td77uzmpoxIknzJSqA6YHJJca0ehSJ640GWvYDjUz1tm5fXIoi0r0oR1GF/i+ulOPc8xy7p28jFB0kwPyrnKNb6Ry0OsLnHaxXZgdxGpJHQOk3VIg2b5/vf1/Om+nlrhtUY0H9Pa7759Nss3qFiq1AFl3slxO5sop1rK5wsrT717cTV6I8OstRgWoJqcPq5T2FpLViacilr7UxqE1EGOVw==,iv:mzfclgvef4xqht5xsSpKi2Dn+3lB86mdd1rxMP5IJqI=,tag:1iyl0/Iox6izmowhQd14Ww==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2tpWmVJazc1Z3RkQXRI
            MWZGaWFFMGo1ZFRtKy9QMGtReTlpbnJFSURzCjJqVUZCUk1RL3dSSGlZUnR0Skwz
            R0N5YndEbFprSVdLSTloS3cxMlRkcVkKLS0tIHNRWTFka1FEZG5QZ3VjWFkwOVg1
            UzdaR1hMaUZlWHNjQ1hOdTM3TGFlVnMKC1hmjbLoSp47P0vJ7iadNQSe8viLmar+
            DM0IdxEdHoCgRtUrxeWshdxNnQDNODKkHLDDi56cH/N68dZHxIZ3/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T22:15:58Z"
    mac: ENC[AES256_GCM,data:Oh95nTgNjpY2DpVDmwyiqPZRKlthlsHx88Q7Fs85di8gSDGshn0N2ddkr9/xCc9LFhAkHBro3fV4+WXd/5nJi+ly21krCA99yKcpirHoPx/kRexPYaQDsW2/GnmMKW98aVrwP373bp6cTSuBY8DHjz/jGjihAiiqfB8GxmHk/oY=,iv:Km6K/MJKKzy8gCCNfpJLBChfb37DokfddXhIUKIue4E=,tag:e2ETUuS1hwOp5oJROqSgiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
