apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
stringData:
    values.yaml: ENC[AES256_GCM,data:AnaSqZI30Q23gH2siVH7r6xuMCOjosCE0LL/kfmMH6W3t60XVPc2KitolpM2MD2Pcm3S+Cpnqnb0chnWxmVoT0wwRYgSUngd1lKR8UgtyZmXh6P0h4WB3IJKUdvWv2IAS2VHbPWKViQF4M6ELDyO7FIyrFnZQ2BlgDGfAPdtOoqfhgBQTXQ8BU2cXZ1KdiYjXbvWu4vDTruLntji/puYxy1kCwV+p68OphKHuvcLi33ANP5ORqZ09J1UNxtAft1DngnSCNU3206026zoKyACXVeQbVFHkzli9DqtgQ==,iv:YOxWWJTIRqUXpYIJ2CtPG88sY346xtoh0SeJZmPKGPU=,tag:UCc70Z/9lhQPTVndU4pPsQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWExDVVZyQWlKaTRieEVG
            cVNYSVpEVTZ4cDJGV3g3VGxGYklVY3ZGLzFvCnRiTUxSNkFBazRoN2lOa2J6cGNx
            c2J1ZlB2RFVSd2dDRExRWi9EZG9MbE0KLS0tIEJ0M0pYZ3VmR1BVMStmZEExN3h4
            aEIrMVV5c21hdHdwWUpYdHIzSWUzcTAKUQetd0S+os9J/9YWn0mlGv5K3rI8A3jW
            xtI/ihE1rVHXrBnyKiD6GOpr246a/hYX/yq3/0huxWjIg4v3arxHlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T22:17:16Z"
    mac: ENC[AES256_GCM,data:ncpEnv6jwWCaO+elIV5y0py4N1LfhlZGrRAzxRWvKbC93unN61K9LZEbepJi8P1mByX9QNJUOQDjmfeA39nezpQlfUISURGA13E+QzB/gTq61ctu7/wBSqlb3S4mOH+2LlMIyxNLm2WPBE3lwkH6yoWc4iEev/6DWDd3KGguRt8=,iv:Uw0pzJlEKeMrCvyrKzXFJZMduGSF/i6+JX4tjYXA6ig=,tag:H6ZpzFylHipfhlsinX8Efw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
