apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slux-cloud-wildcard
  namespace: cert-manager
spec:
  secretName: slux-cloud-wildcard-cert
  issuerRef:
    name: letsencrypt-prod-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - "sluxcloud.com"
  - "*.sluxcloud.com"