apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:x4kePrci9EjvcDDuTjY10/1eb8Y4jymp4Y+uZH4v8hFdKU8UjNrbuQ==,iv:ldQnGM5KezS+k9NmtDJa7VDTsv+E5PSU5JgAUnfpWpg=,tag:8pC9KQDZTzJJeXjzCJMwaA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL3BIK2N4Z3Fwc2tNbEVB
            QXRpb1h6aUhoRHd3cEZvSW1CYmxPUDhhRUVRCkZFVWg0dnBTYUQ1VzV3cEVmK0F5
            Q0RBbThQTlJ2S25wL0gyUHBjdWkyUXMKLS0tIDUzSmNDaTBzcjA4NnAwbnNnWEM2
            NVhiQjV2bnU0RzFNdjcwS0lZVVdxQjQKn0AGdqYb797piA7C+eU46XtLuFij4mzh
            zeqJbZzrS/fZyvtMfyzizv0AWiaRqz7ZS/U5p/n4aT5u8lxDJe23vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T18:48:47Z"
    mac: ENC[AES256_GCM,data:VfFsAzLNgh8V+Lj0ZheK+4tYABf9y+4EIMrlsa0erptmtk+E9ulu7teZzL/1gYnXAMHqBBw+ph4KNZewdMW2WZfEIgHoLc6KHxjnl1g9jDcFo1wV+eOw5ErwThpYcwJ5L8sh6oBFl4YfxF3EIzE8yai2zRNgJvPzEPHC2ffcTl4=,iv:dNQ+VJNOmW/6qdqlmGiubf3C30E4F2jLYLk8ZkpCeFE=,tag:znYDNKWBCQxXjKV+CXAQPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
