apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:FZRg7swXb6KES4IaGh13kZlodW9CKtSYNjxZ4+BGPwqelx269d5/YA==,iv:AywVsAG512TTgm09l8LiciZRy/wEVIzfomL0TZcXEWo=,tag:iKTD+VpjRxXSQL/lCw10SA==,type:str]
sops:
    lastmodified: "2025-10-07T19:57:12Z"
    mac: ENC[AES256_GCM,data:9lxb/ON+zLh71qOobNTbmRdoxcESzZnIRDWd6mcTDyAZMOtuyA71MAxZGCgvG+/vpxXCXmyW11lUYFv8Qo1vKx5hNSLr9SwNpsREUpedcli6zKi9g5YkSLeraPLCBVubqcXymjtEPaB9sD/m2VMAmjBjSrbsLd912Wj/ti4Hn6M=,iv:DMg3wJLkv2e0whC5TblodkwRv35ezITZNub1CCPzI1I=,tag:JRhVEW+dGmp7E2Ca2Pl2xg==,type:str]
    pgp:
        - created_at: "2025-10-07T19:57:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5bcOv4VpS+jAQ//SJXbwRazdikXkJFwYwzE0kscpP9AMvA+gAbHKauAWam0
            YnAT2KDHbtTqL0E4WekkrUjwN8xgnMffvwH+H19AhY0CaJRelQkP7JGnmt+mUZob
            G8drG/27lG7oNx0lYLNKQCvvsPMUjCT8Zb6ZmoD7FSCevqVwLo55cZY7svNVLlkx
            6npEwupOguWrNUOPb8njfiZ8d5dzS/svTJElz0O8RSb1t3xwXvsjCiuouh6d5NSr
            umeHGSBTiyV7rbFBbcLCZZmB0IY6JVmJ3ilvKFud25YMDEuRfqYWzgOI9ff51I0a
            LgpQXFUvYCp8txHC0KyWH1yXLcpoedkfatisAifI1k9Jm4eRx7B89/p/tXRcNEEY
            mYs+AcXa0xmdrchWpuD51mQNnBMqwShN5ALBTj7Cj6Xfp1y8orb6/lXFqa+XqQ4C
            HWDu33eDGfYt0Pb19D7fvCSl1vgKCaA6tfNUYxjj1NQYYKAlG0ZpulrDuECDsn9u
            bY66F/gEpJX2LUdkVD05CBjXAoC88OHjg9RsX20Py28H2JyvdW+RfQmAz3xQxu8I
            1ElSedQGZ4w8zM6cUCxtfgAkUlqsUxO9eOVCWEo5PxkiR7pD2FGZV5bsctS5uVMP
            qDJACMY/kGbUEFBnjbF7fBVTnp253AoNbiJAB9U/aewFq+I4yYfY0RIJllPyzmvS
            XgGtaHyg9/muBY40eY2r2wOj2xXBneF9grdr7GBkipgti/B+rO5jOACGe/9ggkI4
            XDNu7UiqUVRX+sUfJq0y6YZuXrlPv273z+xqaD2FJOKiKcHXphIBzgP10H0xLiQ=
            =/FUV
            -----END PGP MESSAGE-----
          fp: 710CA0F145A7191773CF2271C78D486F05CCD667
    encrypted_regex: ^(stringData|data)$
    version: 3.11.0
