apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:V5sEscxE+2zjVmjb8saWbevnsWv0mTiAk1X+IAACUoSeieapIMChF2ZnD4ryNvab4E2xZSMZhMNR9VUCUFN/chHu6ukXqZy8TR1MEx8ZCn2NQerPIV7nMgrc+Q==,iv:yI/OX2l2+0MbqxpRc0Tc+oH5FQMYdYMu8h047+9JkXI=,tag:kPKPknUSOpuWBPlCWIkJ8g==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaERNeGh0a2hWWTY1aGxx
            S09TOUhKbVFXMFl4aTN4c2NnVkpmWFBvZndvCkd0NE43TmkwV3Zma2U5K1RhR2Vh
            RVZxYWtxN21XRlE4c2JjMTVNRXVsV0EKLS0tIE5RemhUcVhNc2tqQTBzakcwbzVs
            MDBhRG9UdkRkWkZZT0FHU0tObmRzNG8K1cZ6O4KoI+WV7pVIlTXOrdOjXjUjoVYZ
            2dbGxmVkH9LzmAG87ZaiBVkZUOMNazcy3UxaPK5Hi3gJJNJyvgMMsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T00:35:56Z"
    mac: ENC[AES256_GCM,data:O3ggH52MWBXyPcQ+JVZFCYYwP6VMIYx2jvPjotVkNT6ca9QKGO3jUNwmz1NQqBJSQ6balTs/ibCuxb3JkJqUlmj4aNubs4fNFXo85eCeyXR76BD6s8m1H11jxbpD5D6c5AIBKoOCdaeZSw8xYh+Gu8Eg+aNlJV/Wj4qW0g+uwdg=,iv:qKlTp6jHTiJfGZvwLW6Xx7yXP4Yj5UAfMzjNNDmkZuQ=,tag:eMHPD7ONwYOBF+6tjMYjoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
