- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: yes

- name: Enable and start chrony service
  systemd:
    name: chrony
    state: started
    enabled: true

- name: Force time sync
  command: chronyc makestep
  changed_when: false