- name: Download node_exporter 1.9.1 archive
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'
  become: true

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/node_exporter-1.9.1.linux-amd64
  become: true

- name: Copy node_exporter binary to /usr/local/bin
  copy:
    src: /usr/local/bin/node_exporter-1.9.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes
  become: true

- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    system: yes
  become: true

- name: Create systemd service file for node_exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target
  become: true

- name: Set permissions on node_exporter.service
  file:
    path: /etc/systemd/system/node_exporter.service
    mode: '0644'
  become: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: started
  become: true
