apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: &key GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: *app
        property: *key
    - secretKey: &key GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: *app
        property: *key