---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  interval: 10m
  values:
    crds:
      enabled: true
      upgradeJob:
        enabled: true
        forceConflicts: true
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      route:
        main:
          enabled: true
          hostnames:
            - "alertmanager.${DOMAIN_01}"
          parentRefs:
            - name: traefik
              namespace: gateway
              sectionName: websecure
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: alertmanager-config
          global:
            resolveTimeout: 5m
      externalUrl: https://alertmanager.${DOMAIN_01}
      volumeClaimTemplate:
        spec:
          storageClassName: k8s-nfs
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

    kubeApiServer:
      serviceMonitor:
        selector:
          k8s-app: kube-apiserver
    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler
    kubeControllerManager:
      service:
        selector:
          k8s-app: kube-controller-manager
    kubeProxy:
      enabled: false
    prometheus:
      route:
        main:
          enabled: true
          hostnames:
            - "prometheus.${DOMAIN_01}"
          parentRefs:
            - name: traefik
              namespace: gateway
              sectionName: websecure
      prometheusSpec:
        externalUrl: https://prometheus.${DOMAIN_01}
        retention: 14d
        retentionSize: 45GB
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 3Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: k8s-nfs
              resources:
                requests:
                  storage: 50Gi
    prometheus-node-exporter:
          fullnameOverride: node-exporter
          prometheus:
            monitor:
              enabled: true
              relabelings:
                - action: replace
                  regex: (.*)
                  replacement: $1
                  sourceLabels: ["__meta_kubernetes_pod_node_name"]
                  targetLabel: hostname
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
      metricLabelsAllowlist:
        - pods=[*]
        - nodes=[*]
        - deployments=[*]
        - persistentvolumeclaims=[*]
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: hostname
    grafana:
      enabled: true
      route:
        main:
          enabled: true
          hostnames:
            - "grafana.${DOMAIN_01}"
          parentRefs:
            - name: traefik
              namespace: gateway
              sectionName: websecure
      env:
        GF_SERVER_ROOT_URL: https://grafana.${DOMAIN_01}
      initChownData:
        enabled: false
      persistence:
        enabled: true
        existingClaim: grafana-data-pvc
