---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.yaml
  - ./ocirepository.yaml
  - ./storage.yaml
  - ./helmrelease.yaml
  - ./config/alert-rules/system-health.yaml
  - ./config/system-config/alertManagerConfig.yaml
  - ./config/system-config/serviceMonitor.yaml