apiVersion: v1
kind: Secret
metadata:
    name: telegram-bot-token
stringData:
    token: ENC[AES256_GCM,data:IrAkOHh1SVP2Tcn1HlK8wNPNduLwsEA80MYHHNInQyfr5ayYDKvw8l6qMul9xg==,iv:2zfJV3/HOwcnmkCcJ8nsqC5gJ5oxT+53nta6GBRNkmo=,tag:ZOMU2G61DROhdsiVIweHRg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcEh6dVJqWWdGRTIwM0tq
            UjNLL3FROVFBbmY0R05JZDhxUlNqWE5mVUJFCmFSMFVoSFBwUFFldVBDdDliaC9y
            c08wT1F4K21LQytxTnhWaGNsR2h0V28KLS0tIHhpRll1Yjd0NHNLQW5abWpJVHlH
            YVF2NEFhMWZnSnAwczUyKy9BWDBYNE0Kpcg+fPx6+WFMB/CzLrxS7OjKreo0Sq0B
            xA3iuUh4BB/f4AoYES7jBkdI5mGWxNUr1shJIglcepoKWJopmF5jiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T18:07:01Z"
    mac: ENC[AES256_GCM,data:y85zr5Lcd8DBKkJnWu1EMx2RjsVySldJyh157XA4txNLZHD+lTvgG0qV+U575yY+rRBhv/7T2I51m7vaxqHTsxl2CQ6XGNqZAYnqpZvV2e2S0AnLp4FjuGYdEcbNEXaP9LeIUwGO4Xv1v16ZbsF7qui/Hw0s+23tusRFvkPUG3c=,iv:SeaZvuCJKLxcOoeH9T0MObS0IZZy4cGqtU9H/V1qnZU=,tag:CPx/OuVtNgI6g6eJeIHSuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
