apiVersion: v1
kind: Service
metadata:
  name: proxmox-endpoint
  namespace: external-ingress
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 8006
    targetPort: 8006
---
# Using static Endpoints for external Proxmox server.
# Kubernetes warns about deprecation, but EndpointSlice
# cannot be used because this is an external non-kubernetes service.
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-endpoint
  namespace: external-ingress
subsets:
  - addresses:
      - ip: 192.168.20.10
    ports:
      - name: http
        port: 80
      - name: https
        port: 8006