---
apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: media
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}