# PersistentVolume for Redis
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-nfs-storage-class
  nfs:
    path: /mnt/tank/k3s/authentik/redis
    server: 10.40.10.10
---
# PersistentVolume for Authentik Media
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-media-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: authentik-media-nfs-storage-class
  nfs:
    path: /mnt/tank/k3s/authentik/media
    server: 10.40.10.10