apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN_01: sluxcloud.com
    NAS_IP: 10.0.40.50
    LB_IP_TRAEFIK_INGRESS_INTERNAL: 10.0.30.100
