apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    DOMAIN_01: ENC[AES256_GCM,data:3xv8lD0PlemH6bMpZw==,iv:2I/3a4XMXgDCImFlylbLoRGLlY/Y+fQcfHKQA6PBm7I=,tag:KPPRw1ZsXF8EQmNo8T8z+g==,type:str]
    NAS_IP: ENC[AES256_GCM,data:ld8xybL/WLFmyA==,iv:EZhZ/0+XCeQdsR3fgd/7M2eV61gC8kmPHwNFoCtJ7YI=,tag:B4RXzD1F09FmuCDrAKmbyw==,type:str]
    LB_IP_TRAEFIK_INGRESS_INTERNAL: ENC[AES256_GCM,data:qm38VrNtHJrLXOg=,iv:d/Y0iufeyet3uwC3WOHb+5nuBnfCSzBOiYm4qwFf5lE=,tag:eoFsjq1CijoAVmWfKVnIGA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQmdkQ1dTdWh0ZE94QWpx
            b2RXVVQzanlQamgxekQ2cWd1NUJDanpsQ0ZZCk81anJNcXBrVklLK01SaGNQMDJ5
            dG1SSUc3cjRPZ3drS2dWMzFzV2FUZmsKLS0tIEtwRnQxc0w0NHFWRWVNOE1yb0RB
            QlhCQnhBTGJCdFFEUVlTSHdLWjVDancKY16INdLHqEhgbH2oxTwbpy3fIrRWHTau
            vC7ld9n96AX2X1FkJ9yOIOr4SsTdl8PR3AeevAQ6rASWzQNm+C7ygQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T13:00:26Z"
    mac: ENC[AES256_GCM,data:eiC0l6EtpdH45HUfas4N86Z47SJJomEMLvOhAMnydnLQOyFVirI7Kx1TfWW4KhryKFXgw9kupiKTB+/S0DbdRLQKgsesux+GjsIZnhr+j67GtSK2yiLB6JfdxG6lfazue2OAma4CjdxiLbB00q8w+pbbH95HsoxnbMp1Rn4wVC4=,iv:k3okFOGADY0fmWNS/cCE8CNz0qgR6m6jR1JVaHaDVTk=,tag:GU/VGdzDZLOeLhoWaHfAPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
