apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    DOMAIN_01: ENC[AES256_GCM,data:dUOZsVJln6e/tEo7cg==,iv:udUj7aVAVlGLy41YxKwgD1Gm7OwOoCGUjCO+XM2PC9c=,tag:DwAVRLL8ydpHYcFJQEOWug==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VXqubIk/32sLaPwM5d29nU1vJXHoOlV9/XVD8nI6zHKCbW6m,iv:nyCFdOnezr2vCwrb17wR5M+q8OFb6bsONguMoEq2Mv4=,tag:zUeM4p1VyadIdoEZjVbEvA==,type:str]
    ASGARD_IP: ENC[AES256_GCM,data:aXUhUA0hpcJydQ==,iv:yACc99EPZw2eDHSgxBoIidOJvCeZ2Dsm58m8lj/sTik=,tag:j0MBvtc0q4Q5MZb0WiXtsg==,type:str]
    MIDGARD_IP: ENC[AES256_GCM,data:mGelKlTFMAhuHA==,iv:f1aP94ENJOECZ/sTzPkNHRNjzWd2RI0+rz6/Flk1NRA=,tag:YIUARpbZNQf16i4qbFTUGQ==,type:str]
    MUSPELHEIM_IP: ENC[AES256_GCM,data:9fyX6BsyOIhQtw==,iv:QMrhsi5TElbiIxS9PV+rZ9f20kp5CgQBf/qKlBYxu5Y=,tag:jc8ncgjpaBLZnY4+O7nzNQ==,type:str]
    NAS_IP: ENC[AES256_GCM,data:Rd+VIKHbAJIFXw==,iv:EK4vRGffB4CL7d+1zEul9HLFAxGOUHF6STnjuxwU9gI=,tag:uoWkiHX6+vGJxNWRAzRq4g==,type:str]
    GATEWAY_IP_INTERNAL: ENC[AES256_GCM,data:YcuBYosC6VYsk/k=,iv:eK/G2kn6yh+KBmQ+pqlSZHDfGIMHo20uVdLvcqNJrOc=,tag:TINmpmpJoj7R4lvnAzq5kA==,type:str]
    GATEWAY_IP_EXTERNAL: ENC[AES256_GCM,data:ycRijCoOLJqfFFc=,iv:xk0/Bk/f75RRiwnc/LZj3CfsXiKL90Y24rkWo4V0eZU=,tag:FSfXcr/aE8cb24BtNt/vcA==,type:str]
    QBITTORRENT_IP: ENC[AES256_GCM,data:nYivV8BExNn/3QE=,iv:tFERqUa0GyqckBFaNEmVfNHK8PBiUfNyfO0uyNNjkMI=,tag:bSEPZmmqIfcSkCjrlmCLOA==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:i7v/YiuqnL24Crc=,iv:YTT2eM9BaxX1OsLwjDNwPt1Za/BDP3RO7InhY520cAg=,tag:Vrs9dIgCNZmSIwkb8iOk7g==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:i6XazLyWfAjk9bXQyH37+A==,iv:xnSl32MX4vjpC13r1GYLTtdSh+exemg0yhnrMJ+bXyk=,tag:SvFjB0kE78SQ0GarLMZRtA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVRZZDdodmt6YUI4S25L
            ZExHZ2VBN2Q4VjZNT3dqN3dMek1FNENYd1FFClkxMEJvL3FSc0wwMUg0TnhIVFJS
            Q1A4UjJxZlNXcUZPR0MyR1FCUDhYK0EKLS0tIEE4Y0dzQ0tvb1Jpd1RnMVM4L2Ns
            TW14d1o0cmxyYlFUSUtXWmNGcnl0amcKF7dxQopfNZrNyZufY14BDcrqLULHNBPs
            hiuuYqkP8Z1UKR6nYwHpz7EYuCbvqTOnbFPVyDIBlo8wWeYtrHE2nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T22:16:25Z"
    mac: ENC[AES256_GCM,data:kC4XrYzkLGrsMRzrjyYRp+nYofTSXArw6wroJwzzJDiETAgtn9M9JETH8B96Jv0IOObb3Mi5c4zmlfWkb3lJlYgavojH06WyG4CaK5sSZAZ7v3lbFM0pYLw+quTgPLvrQHDvSUTbPAaJmUIizTFaBRUWlItrv6AU7PJ99GkQcq8=,iv:lqjyq14WMtMcXnZHMa7BM3C8PYboVKqLZD+9FWVc7rI=,tag:un3hHEnE+IWVjMtFkttYAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
