apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uLuSzH8YpKeYqG7tIQ==,iv:oWzj4P6yYl24WSEJ3SnJa0R1kvycpOHJb0W28Gb3nHQ=,tag:TkdlT+wEX5kkabG1XQ4pbA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTk0zOHNYRExIeFk1bm1M
            cWJjVC9seVkwTjhiUDNMY090MG1EMzQ5Y0FnCk0welNmM3hNckdqUjBJSkFhRWZu
            cGkzNk1Sa01ERjlYZ2xjMmt1OGRsTXMKLS0tIElnOGx3b0p3NmtWZ2RTd1NPVXlS
            RHJuRkhtZyttQ2dyZHJaUFRvWHB3dEkKs3csR4tqdzxc0hkWdUK4BxxTpvnwuDm0
            csCCyFWvHNhQnP7bI5sCgM1ABeOEaV1bjubkCtqI94QFy4YrgPVWtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T23:18:29Z"
    mac: ENC[AES256_GCM,data:zJZaDO/e0ZvFbBn0mkjGqY4+MXNvM0Vd1BMk0Mdg0L0JcBcLCuce3nVtT7i4+aMYW/vOeswSFaiSeWBk/KTqkoclsuMiOWFecHA3PLoHflaAj3A/b6K/z8SSkfvgvbIWoD2pDaEM0wZAJspMfLlWSppKcsxfRyAORrUeGYdYhEg=,iv:e+qgkQhhicn6iLPw1dh26A6nkkFV3JONfmm6FOn32sM=,tag:TvGi8A/QbcRTuWDDD29KrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
