apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    DOMAIN_01: ENC[AES256_GCM,data:dUOZsVJln6e/tEo7cg==,iv:udUj7aVAVlGLy41YxKwgD1Gm7OwOoCGUjCO+XM2PC9c=,tag:DwAVRLL8ydpHYcFJQEOWug==,type:str]
    ASGARD_IP: ENC[AES256_GCM,data:aXUhUA0hpcJydQ==,iv:yACc99EPZw2eDHSgxBoIidOJvCeZ2Dsm58m8lj/sTik=,tag:j0MBvtc0q4Q5MZb0WiXtsg==,type:str]
    MIDGARD_IP: ENC[AES256_GCM,data:mGelKlTFMAhuHA==,iv:f1aP94ENJOECZ/sTzPkNHRNjzWd2RI0+rz6/Flk1NRA=,tag:YIUARpbZNQf16i4qbFTUGQ==,type:str]
    MUSPELHEIM_IP: ENC[AES256_GCM,data:9fyX6BsyOIhQtw==,iv:QMrhsi5TElbiIxS9PV+rZ9f20kp5CgQBf/qKlBYxu5Y=,tag:jc8ncgjpaBLZnY4+O7nzNQ==,type:str]
    NAS_IP: ENC[AES256_GCM,data:Rd+VIKHbAJIFXw==,iv:EK4vRGffB4CL7d+1zEul9HLFAxGOUHF6STnjuxwU9gI=,tag:uoWkiHX6+vGJxNWRAzRq4g==,type:str]
    GATEWAY_IP_INTERNAL: ENC[AES256_GCM,data:YcuBYosC6VYsk/k=,iv:eK/G2kn6yh+KBmQ+pqlSZHDfGIMHo20uVdLvcqNJrOc=,tag:TINmpmpJoj7R4lvnAzq5kA==,type:str]
    GATEWAY_IP_EXTERNAL: ENC[AES256_GCM,data:ycRijCoOLJqfFFc=,iv:xk0/Bk/f75RRiwnc/LZj3CfsXiKL90Y24rkWo4V0eZU=,tag:FSfXcr/aE8cb24BtNt/vcA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:7MCSNaxSG/D0u0i7c1s3a/Ia06/biSXuiJnf3vS0YeYrBctpjVpleBZNlBP1Fh7rnkJAK2mV+S+p9g3CfjfIDS4egy7MJFsmkiuGDZE+/dejzYA4EcnWzhpB3sXo,iv:O2Ws+aKJIH2SQzTJX1ymdrDLLfLQGyietRQQnr+HjWE=,tag:IRWep0yqc3v9gZ+fEBnJVA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVRZZDdodmt6YUI4S25L
            ZExHZ2VBN2Q4VjZNT3dqN3dMek1FNENYd1FFClkxMEJvL3FSc0wwMUg0TnhIVFJS
            Q1A4UjJxZlNXcUZPR0MyR1FCUDhYK0EKLS0tIEE4Y0dzQ0tvb1Jpd1RnMVM4L2Ns
            TW14d1o0cmxyYlFUSUtXWmNGcnl0amcKF7dxQopfNZrNyZufY14BDcrqLULHNBPs
            hiuuYqkP8Z1UKR6nYwHpz7EYuCbvqTOnbFPVyDIBlo8wWeYtrHE2nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T18:04:47Z"
    mac: ENC[AES256_GCM,data:axT05IaLGoacZBmSJgPopAUUHrriGZxJkUwpKQ9/zjYYPeqFXQZWa+XV2YPL/UIhFwNOI2gGwQB6KKnqQQxRO1vsLiJ4ofl3L35dJd0/19hzOo51knFO5HU6bX146q2zHOJtrxRgerlfDaFWRC1sYQmkUtNyeRQ6miHTuhjKOLY=,iv:jiKKxQYJObnNrOKOfNELiCDS4JZi9SpMHljHrTimn1Y=,tag:nJIHwyTQaomc2pJ+OZoSVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
