# monitoring/prometheus/persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-nfs-storage-class
  resources:
    requests:
      storage: 50Gi