---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: seerr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        seerr__AUTH__APIKEY: "{{ .SEERR_API_KEY }}"
  dataFrom:
    - extract:
        key: arr-stack