apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: 27.45.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
  values:

    server:
      image:
        tag: v3.7.3

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - prometheus.sluxcloud.com

      persistentVolume:
        enabled: true
        existingClaim: prometheus-data-pvc


      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      
      configMapOverrideName: prometheus-config

      extraConfigmapMounts:
        - name: prometheus-alert-rules
          mountPath: /etc/prometheus/rules/alerts/
          configMap: prometheus-alert-rules
          readOnly: true

    alertmanager:
      config:
        global:
          resolve_timeout: 5m

        route:
          receiver: 'ntfy-default'
          group_by: ['alertname', 'cluster']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 3h

        receivers:
        - name: 'ntfy-default'
          webhook_configs:
          - url: http://alertmanager-ntfy.monitoring.svc.cluster.local:8000/hook
            http_config:
              basic_auth:
                username: alertmanager
                password: verysecure

