apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - secret.yaml
  - storage.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: prometheus-prometheus-config
    files: 
      - config/prometheus.yml

  - name: prometheus-alert-rules
    files:
      - config/alert-rules/system-health.yml
      # add more like above

generatorOptions:
  disableNameSuffixHash: true