apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: prometheus
stringData:
    values.yaml: ENC[AES256_GCM,data:iJJLRSBBVg7Sm/q8x8AE6euIAO7B8FSuMhKCNKG2KKBd5QrqqZ0Sj2aymMHIggWE9iHNpmP4GLZ9oUe1CUjbLQkSAy04rlccLdOr5Fc/mOx8D/zfqOcUGZ6OauumGoPgokcsh3COiccN1gGrI9NDXs9UusJjNhgM3Yr5rx6qbzg6pz80jyNfF6nmtYEaRfX4grIo1JM3xdJ0obvsNNPvWp0FLaemhcElBaYiy3bBQ211VO68uP2D8r1PoOMwLkuRr6/sKl0v/Uh3OFwHeXtMpHP/8MvxJff7aTvBBW+5ikIsY7WSxv3I5ptaWIby36QYOJ4pLfpC85mfCwxzcpvcTzf5AX01zJvE0hkR+b8yiYoKS/L0d+hOUKBo/yAfPt9T,iv:nNYGmz0rIUgRoaUOaQh1KD86SATss0JAK0pfESN9HEg=,tag:Ri7eL5upwFZajm3/kbDlpw==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGdsbEFDNVU4V2c3ZVpm
            VTVqZTdnMFZrb2tGSmZwQVFGVER3SE9tdzF3CitTYUVCTFVSU2FvWjFEalBQZ05p
            Y1Y4MWN2WmlVSEpGcTNpZXd0ai9NcW8KLS0tIFVWWmJCUEhzSFFXaERyWUVyam9x
            MTNqNnBubzFxeGtDank2WDYxaFQrN0UKKEHgr3RS61NLf4uVnkLsziye5ppvuuBQ
            PIovNHjzJGEJXomAYfTxIktlhmEVQMNfu6w66tL4YOArqLY+NZDG+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T23:24:15Z"
    mac: ENC[AES256_GCM,data:ylW3FN+9WjWGaRPdXVIxyPOEM6HXe2NaQDdDPUGn3qCcC8wbTFSPXcs8ZIZFsOrJYfiWc+Wm8r1MvfYgsWM1mnIF0s9wFP6qeX3grup1bTkz2BwEi8LaNAQ9ZcS2nwrxXKkIkoS5x2SV6v7hwisVJvNGZvCDYbULYfiBjdXDOmg=,iv:knA3v1m5Ob2ycYdB0SBM3+shpH1EOVASrKkrbIsXodA=,tag:2Od58q0SX6ZiEIiSD6JE/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
