apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: prometheus
stringData:
    values.yaml: ENC[AES256_GCM,data:sbiFVqZnL7SlNa+QinLwrSmuVwcsJOjuC4BdJOr8mD/OTzwa3CoHmj2/RC4nJcBzWffr4/zLbPgjp/VcJmA4Oev4s4SQFun2Pn+zP/AAEpTHkQT717YHFg0XL9sP+ozE8K8EZ5Csg90WJE5LTD3lXW3Lkj2iAp7sy5m7ebLkQMVBxGxmwHFNpz1MQsBN/r+Wo6/bi1iorkmyjAPC5A+D0HvtVGHoUmt/F911cRM8CJao7GZ9Bbkdtevy1R0m225lQjZ3/3yxTTDiB1mZ5JsbKe5kkLCzNf4WHLMzlPDBdPkrN39NC1MswBwaOXvTHxIUODIoT5fhMzbtTYeRoNmczRsX5jh5/v/WNrp986YgENjQygMkYkyrTFp3nuYTAvQh,iv:hUZhFJszWEaNtO4Fl4/E91iONb59iEOvtWttPhNjzow=,tag:viz9XbetdkAC6SuCUHqMhg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMkdsblpkNmdqOERDSWlY
            bWZjWDFQY1ZoS1FjWno3eVp3Nk5XcXZST2xJCjlLNHBLTnpJT0xvcC9SZFIzLzlk
            bFVwV1lxa3AwandzQlFVVUhXZCtUTmcKLS0tIEUvYk1GaExQbWFTSHo3Zk9yME1D
            eHJiblVvdXNwV0k3WDlSckczWVBaamMK8z7RvjixF8AEURV3zGFVeACvI+gLySDa
            b376kKR7coi2xmDqajFzbSjAQs2BjvvXwl3Nj5blEpV976Fr9w12RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T23:35:46Z"
    mac: ENC[AES256_GCM,data:vUw6blaAmnvxd3XcfUORSr8a5gjviCZW264Rh26OxBRmpATrNLw24mfSZ9u8WRngCZcqmCUx8hNnvZiQLIJ83SMlE6YfmhMxMH09/q9FuVr2xf48Zh98czBceXbn2/cZ4P/cGpqH36/OUXzJ1wSOgmGROwsNabHLWcjH1jwzGLo=,iv:H/eZC6Tpqwo4bsJOyiLmvAot/ZLQLmAKeoZKGsJ1tXU=,tag:/rY1HEPERGkAs2uDT798lQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
