apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: prometheus
stringData:
    values.yaml: ENC[AES256_GCM,data:EIHr+YHgsZ7LR4NRRKHRkEnizsBl7yvwfoeigfrxxDi9DjWusg1qMKfDiAtEKIt0379E/WzwmNpKxQ/Oxfz4gOqucBjMznOGS6Oo7H8PDS/1sL+93KUGQS60m1KmPqWZJuU+OQF9wcW7bo+9oNmiBhUtzLEniXGvIVjzW1oXyjwL0vh/FktN5NfBB5DmVzb/f3ZZ2Tndl7SMN47WVizIxHz+hn4LVuz4TINbZ1rFRHdKGkdQQuwE8J21RBfQeMqLjPcAkB9OlCpmJJQwR4MKk9zhhX2ZhnmtfgbMhAdWPfP5TVwA7FglN+yOxTWRKY53BEvABA/bmKQ3O4hd3I9a8rKZPNWWmMHvR7XYUwLXC3sn3ACNHsqjTzb87c/J7fGufhAU2JHdVBbAyg==,iv:TrfuZoLQ4lyJWSlBHzQ4OTdlwWHMI824DG6zBD7n+24=,tag:AzshrsqQ+YaVfuy1zxTQTA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SnBaZ1dzQXN1V1VEQnpL
            eWdtNHhPQ1RIN01Pemx0RW1NVEpVd2p2cUMwCkhMVW1sUVVzVUJ3ak9wNk92RVBO
            VitMb0tHOVFibk1mTkpIMWpON2EvL00KLS0tIGh1R1FJVHR5NU5lWWtHSXZSTC96
            OHo5eGl2emFCSXJKY3BkVktlREJDaGcKW985A+fZg5p5ejYZXhRgJO36in4eHEzn
            wVWDk8iLw+CfG0tGNX9ca++13XGZCyeXh1lFoDHybMXG/cS4Uor+Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T23:45:54Z"
    mac: ENC[AES256_GCM,data:+j9E62zZHjS4tqQiFuw/FTAXssVG4hM/b6xq09onmVsjpVsrBkouR16y4HNUIW6nqfkNnkhPk/bcLo7yQWq2rJUO/z0zUQeCdQ3lKXhdaRaL0kBFOHCcp/V6MYEyRSqaAlElk0lh4KHj5mNmIM0PHtG+sJV6i+uDBVp4O5OYfcM=,iv:Yw4uIScyORtAkceur3QMbzq4naRZ4jTT87+tdeKIwkM=,tag:PgXNf2YvWGKdrJlAzIjimg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
