- name: Check if cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_status

- name: initialize K8S cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all
  when: not kubeadm_init_status.stat.exists

- name: create .kube directoryi and copy kube config file
  shell: "{{ item }}"
  loop:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
  when: not kubeadm_init_status.stat.exists

- name: Check if flannel is already installed
  shell: kubectl get daemonset kube-flannel -n kube-flannel
  register: flannel_check
  failed_when: false
  changed_when: false
  become: true
  environment:
    KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"

- name: install Pod network
  become: true
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: "'NotFound' in flannel_check.stderr"
  args:
    chdir: $HOME