- name: Initialize kubeadm
  import_tasks: kubeadm_init.yml
  tags: kubeadm_init

- name: kubeadm_cluster_create.yml
  import_tasks: kubeadm_cluster_create.yml
  tags: kubeadm_cluster_create
  when: inventory_hostname in groups['kubernetes_master_nodes']

- name: kubeadm_cluster_join.yml
  import_tasks: kubeadm_cluster_join.yml
  tags: kubeadm_cluster_join
