apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    api-key: ENC[AES256_GCM,data:Td6moa+DNFtnDlKjnkCDGagj63eTK2NUO1EvY56BNew=,iv:WYMqfQyr8U6X1xnH9LXWp6XujuqOrvkXVl5R0zaNv6A=,tag:K9ZrfEGEbb/nMvlRcqb56w==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUDl6QUxvR3d0Qy9zY3A5
            YkFDN3B2UlVBRHRJTjNsNFdaTkhHanFPMGljCm9KVDFWckR0aUVidzhVSGxrWGFR
            eERTcHRPeHltRFplOTFZdHUrdTl2WTAKLS0tIFhsam9vb0VZd0YySFd3QWN2ajJZ
            ZTJTTmJxV2VEVmtLWUxicmRJTWtTQjQKSZ3bvcXhFmckix9zq33ZwwbLBaF25BB3
            0Olx3AqQ5v51ymsHLT4O7qRYEn+wACD7ewapk/5hc/hbKiU+E1UyTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T21:23:25Z"
    mac: ENC[AES256_GCM,data:4TZ3hrLrg0XeCejzhJs/vo8v2ikbo96YOvFko3/a3QbhNx3U1ZyN4IhgNiuIoMii2I6w5oUkqarCKQIhx3lXBk8qePHRjoOGaj5a2lZ1TPhmaGJVsbKCbhHY/fBV5UCpiBry11xFsnStZlwq4HpdcSHfBqvKIki6YYrihIK3SSk=,iv:sw1Nfgar+T4WHgOvf8163n5WqZ4GREMQuH+HJdKywgQ=,tag:524DiEeUTZ+MriZg+YTrIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
