apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  route:
    groupBy: ["alertname","job","namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: "telegram"
    routes:
    - receiver: "telegram"
      matchers:
        - name: severity
          matchType: "=~"
          value: "warning|critical"

  receivers:
  - name: telegram
    telegramConfigs:
      - botToken:
          name: telegram-bot-token
          key: token
        chatID: -5260415517
        parseMode: 'MarkdownV2'
        disableNotifications: false
        sendResolved: true
