---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filebrowser
  namespace: flux-system
spec:
  dependsOn:
    - name: onepassword-config
      namespace: flux-system
  interval: 10m
  path: ./kubernetes/apps/selfhosted/filebrowser/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  targetNamespace: selfhosted
