---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radicale
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        users: "{{ .RADICALE_USERS }}"
  dataFrom:
    - extract:
        key: radicale