# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  interval: 10m
  values:
    controller:
      replicas: 1
    storageClass:
      create: true
      name: k8s-nfs
      parameters:
        server: ${NAS_IP}
        share: /mnt/tank/k8s-nfs
        subDir: $${pvc.metadata.namespace}/$${pvc.metadata.name}
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.2
        - hard
        - noatime