apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-nfs-fast
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.40.50
  share: /mnt/apps/k8s-fast-nfs
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - hard
  - noatime