apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.13.1@sha256:4c7742f9661bb290c65a97701003e579129fa9d6d86f63283604131db2796ede
  url: oci://ghcr.io/home-operations/charts-mirror/csi-driver-nfs