apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-values
  namespace: immich
data:
  values.yaml: |
    valkey:
      enabled: true

    immich:
      metrics:
        enabled: false
      persistence:
        library:
          existingClaim: immich-library-pvc-encrypted

    controllers:
      main:
        containers:
          main:
            env:
              LOG_LEVEL: verbose
              TZ: Europe/Amsterdam
              MACHINE_LEARNING_CACHE_FOLDER: /cache
            image:
              tag: "v2.1.0"
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true

    server:
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 1500m
                  memory: 2048M
      ingress:
        main:
          enabled: true
          className: traefik
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: immich.${SECRET_DOMAIN}
              paths:
                - path: "/"
                  service:
                    identifier: main

    machine-learning:
      controllers:
        main:
          strategy: Recreate
          containers:
            main:
              resources:
                requests:
                  cpu: 500m
                  memory: 4096M
              env:
                TRANSFORMERS_CACHE: /cache
                HF_XET_CACHE: /cache/huggingface-xet
                MPLCONFIGDIR: /cache/matplotlib-config
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
      persistence:
        cache:
          type: persistentVolumeClaim
          existingClaim: immich-ml-pvc-encrypted