apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
stringData:
    values.yaml: ENC[AES256_GCM,data:hM8OGjNF1GEI+yTn0Xti19hQp8dLE/BZutJsp53BBWWfM79ZP3b364+eePossY2Lzjjse9aWbXE4gTvwJ/JYvK5Hl57GAloq/guNULg2Ec6apH89NZ//538rirPZ7BiVOudbVrqrkZ8SjXrrlHnRDqs9MyKfRilXFU1RysXRAS2z7jFVsyrfy/HOPKqCvSW7L0Yu1qLvbO1i9pOieCg8/7MBnOMSPVlYAr4Yw0RJw+qgQNadR725Zk7+D445SEpLjjwveTQQC+HBYlmVjdJ0Nepcflvvlssf/sc=,iv:01xij1zd+LcI2gsvylAZVs1WUQTGDJSsvNtXKaxahbY=,tag:ZCfmCx1M2vJJZILVBOfh2w==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2tpWmVJazc1Z3RkQXRI
            MWZGaWFFMGo1ZFRtKy9QMGtReTlpbnJFSURzCjJqVUZCUk1RL3dSSGlZUnR0Skwz
            R0N5YndEbFprSVdLSTloS3cxMlRkcVkKLS0tIHNRWTFka1FEZG5QZ3VjWFkwOVg1
            UzdaR1hMaUZlWHNjQ1hOdTM3TGFlVnMKC1hmjbLoSp47P0vJ7iadNQSe8viLmar+
            DM0IdxEdHoCgRtUrxeWshdxNnQDNODKkHLDDi56cH/N68dZHxIZ3/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T20:39:09Z"
    mac: ENC[AES256_GCM,data:55TFYKa51Hs6HaW2s+wwE1e37uUohjFxRIw/oQn6KdC9ERQaPbspZLHw9vhsE8nPx/p7YfM+0pYpbyXNpgdOxPKwYVnzMSRcHEoNB2k5Fq7giWCGNX881N5NNRcapFiFL3SycJV6kIbSmpohxzLzSu1ql+tKnIPvbiUkblCzGNo=,iv:ZeOUDquJ60gf1dmmvd2J6kXoFKch4/P3syqrzo8D3Jc=,tag:DtgDIzmftoT+K0u9OomkSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
