---
# --- Core Cilium networking ---
routingMode: native
autoDirectNodeRoutes: true
endpointRoutes:
  enabled: true

ipv4NativeRoutingCIDR: "10.244.0.0/16"

ipam:
  mode: kubernetes

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

k8sServiceHost: 127.0.0.1
k8sServicePort: 7445

# --- L2 announcements ---
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: snat
  serviceTopology: true
localRedirectPolicies:
  enabled: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
# --- BPF / Talos compatibility ---
bpf:
  masquerade: true
  hostLegacyRouting: true

cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup

cni:
  exclusive: true

# --- Hubble ---
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow

# --- Prometheus ---
prometheus:
  enabled: true
  serviceMonitor:
    enabled: false   # flip to true once CRDs exist
operator:
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false

# --- Rollouts ---
rollOutCiliumPods: true


# --- Security Contexts ---
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF