apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - default-deny.yaml
  - allow-flux-system.yaml
  - allow-same-namespace.yaml
  - allow-dns.yaml
  - allow-observability.yaml
  - allow-http-https-egress.yaml