apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-operator
    namespace: ext-postgres-operator
stringData:
    values.yaml: ENC[AES256_GCM,data:KH8CQhO++EnphgghfzE/81GZ1/keJQO3eQe4bqwLi8yEMOYMWLZ7zEHIfeDrA6jpVlLFPmWMcWCRtvG+tGVa3WJHfU4BrorW5Z9E58b/llg4fl+AAvkP+S5o4kcF1tBCyoA2SyUSd951Y2Zp/gVm4cmBhO392IC8zsdPwnQIbHp3Xq7zMGcYgQ==,iv:vRj+WMoO4InSzGgzoL4fFX3sTajw/iJG+5XLmM6tN7A=,tag:KYiVhvqNrzxEDnWLXD8CCA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQk9Wazh3bFM4djkvcDB2
            eURQejl2TVpjMzZxdDBad0VJdktYdkFldkNvCkN3bERleXViVFJlREUvcVU0bkJk
            U2dDNERnaEVHOEpERnBJQzR1OWVicW8KLS0tIHQrREtnWnB4ZmkzMWkxTkx6a3VJ
            M2dtVWVMM0o1REs3REpVcDBMWUJLOG8KjSLSx1/L3kXLOTsc116B6yCYcS4mqBmX
            l9ig+sHXEmmwPvs3rirMEAzGG17LlHx5D3PFa4z4BiLNfE6b3PMmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T20:33:19Z"
    mac: ENC[AES256_GCM,data:A3LPQiKa2YmXETlIMVxwhE9mO0PbvWe6pdO2V2BVvtCcdCBdnl+BVXlgL6gTm/diqDyRPDhz3CMU4peqr13l5H8TENj3vs0KLZJKi+QiI9YGRm+ezpQxyUcb75UQVOOsrC1oXyZdWKzbgFB7t4+YVbA3oTeLSOMSSAuLGyFMUnY=,iv:sMyVCSm047Wf6srjM+93plPL4WWWMLhJB3YQMiy1TXY=,tag:b3FGExrbosQ+mBryC8OpUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
