apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  POSTGRES_USER: "stijn"
  POSTGRES_HOST: 10.40.10.10
  POSTGRES_DB: nextcloud
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_TRUSTED_DOMAINS: cloud.slux-solutions.com
  NEXTCLOUD_DATA_DIR: /var/www/html/data