apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:TmC/PfBcdclm9uebzljy2UufQ84OdtRZEQbcHFpHgVJsIkUNMWnpuPEKriVqjBpJKXSJwsl/j0qkJtnryTqx6nMEDHppHN4XWy+7PC4P4wAiMgE6A0PMDezKZmGdPI0hd+gk12eRO52TsW3x8EmjgM5TN5XXrrV/Z6vhHkRJIkxqZBd2rsN//IYEZAR9l+cnbSudru3YfrlgK0+gMHo3Zjg6Kwx8ZTuFaSz6UGwOUzMa0XMH7fOewZ1NaZCuORm8fEie6Y7WplvuLoMakk3PK1PIxaJnaKEARhA9flnV9oXO6rg4G4kWTfKaLPkNVm4nWbRYZ65TU8iwQPsMmFRAEcBRSJsMxAsIEujM3KeRncLUs/Zn3Ic1rWmRkFddAuxTuGMYafSKjBrFnfmKyaUT5shjX24zcw31tggaot28Ai2c6tpAa8yW2cBjua6i7qYhaKrxrWm0cULuxzXJ7B6vyGeZmQCWfgPMWMAXPnp0B2n0dSenp5oAuL1mPRhVQVX7uxJC3j8gF1zB0txzH4IdkEljIyRIbzjdIyGfZikwsCSxGb9aDIwKstbbyG8dJWDc3yvQNolmbWWdT13Sst07LGsfgY+Ge8dgH9OUoUpdqSOCWf4J2KGO7wvTYU2QTJwiecyTl4SYkD8RrBLC4YI1f7b587wFDI1Y7uslS7P4jTSBs+fkPrOKAV53PdHr0iHKwBN6lLq9960Jk/z/y/FK7mhoulr63VfIAAd2u0fZm5RgrcLWJZVRShZHBu2O+6MncSwcSGSOdy1EJIZhGqU2cooXp6tijnehrOgnahyBSk7/UfeIVauKNyinsXp2ODFOswBofI2UxZtkZjTA/5hQ47JC,iv:/+zOinvV0C39Riy4J8HCi4DzkY5N9aX5vS4qXS8gVx8=,tag:G5NduGLpzdgpC/iy3gsvDg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSTFPN0J1M1ptV3lLNjRv
            Q3FxTW0rWHRkMlY3Vk9NaUttSkhVK0pMdERvClNNTi9DVnI4VllsTkhFcDM2Ykhi
            QTVkbExjeWl3YnlXYlNPdlR0a3M0TnMKLS0tIDNIUXkrcnlYa0lMdnYzeTlPYXo5
            VktsRm1pa1pLdmxlUVJNMURSaVh1N28KFClY5VExoi1OKETcqSlhRxcjX+ZNryiE
            wriDCnDmxJXZrTLBmD3RAB1T8kDkJIRiIKc9NApJIFSytuCGw50FMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T23:35:19Z"
    mac: ENC[AES256_GCM,data:f2NMzBqFjnSl2NjGAy3gK6hE9yG8eODfWiMWykVxq5tcHZ0CVXYxt1iQNF8QKvJiFbzyB0c8wcTu7Jazmn5nHu1X6YVk1RTRT1RUK/48V9hC4TXVg+85J3Dgfg7Y9qCJDpZqxWijLXol0OL2PkKdMVt9x9k7RtiCWhQmxjiNp3Y=,iv:m3TwJMD58dlliMUqI+1tNtasHAvTnIlEnTyq9MBFSNw=,tag:5n8nBGKCumL0bT+iE0vU6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
