apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: talos-node-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_endpoint_node_name]
          targetLabel: hostname
        - targetLabel: cluster
          replacement: talos
        - targetLabel: role
          replacement: controlplane-worker
