apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: internal-gateway-policy
  namespace: envoy-gateway
spec:
  endpointSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: internal
  ingress:
    - fromCIDRSet:
        - cidr: 192.168.10.0/24
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: gateway-helm
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-gateway-policy
  namespace: envoy-gateway
spec:
  endpointSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: external
  ingress:
    - fromCIDRSet:
        - cidr: 192.168.10.0/24
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: gateway-helm
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cloudflared
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "10080"
              protocol: TCP
            - port: "10443"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: testing
        - matchLabels:
            io.kubernetes.pod.namespace: cloudflared
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: gateway-helm
      toPorts:
        - ports:
            - port: "18000"
