---
- name: restart chrony
  systemd:
    name: chrony
    state: restarted

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: Restart networking
  service:
    name: networking
    state: restarted
  ignore_errors: true