apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
stringData:
    values.yaml: ENC[AES256_GCM,data:W7HyWs11z/vAtHwxucKfraq/kLrkYSelhkmZhhuNMXyGWhvdh6Ajtjk2Ws7a/Va94NHd0TWUVX9UuMcW8IYSw+wT/5RI2kZJ00Ix1db3GaXo3vlUv3HPnXyDi18R+ka8rHw2MZAz7nw0Y4qWElNyMDBf3NLDQL0D10OgROEn3lP0BIx33LwiKXJoLc55iVrBson1NQBRUqls0dg9J49ASJ9l8hTaCg0bftRtnKwjxUDlw5gMnyk1kvYNRE5+EroUDMu+OinmtlvXkvBZJblXea4vh3cwISYZ2OP+KA4T8su+JJV88Ok7kK+G7AMNPDYabFAEtVctclwN,iv:7yt5xLT13VNsOVc2sk0EOQpLJy7eclFwkCEfPWo9RLc=,tag:9zhluNOagLc+K+VoYfrQ3Q==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHMwTmJHTFlBMEJ5blZm
            V0w3NlBKdkRyb1UyeHc1bzBGT2htU2dGcVcwCnFwLzVqQkpjMlBGeDMxcjk5ZThQ
            OXRhYUJOb1BuUHZuL2xYYWNzMXY3UmcKLS0tIHZNKzk5MnNvVDlrVUlxbWhETFpS
            UExXUng0T3UxWUY2SXd5ZXdCcXpacDAK9zQIh28Mko2aV5Yxl8feK2Sbmf5xe7/O
            NKiB3i8cVoFc38Hnd0SKYfMpTToOZSNTDt/Mz9FKhmrV5YZGHJ2PRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T20:33:22Z"
    mac: ENC[AES256_GCM,data:ctjQAKt44eEvIrnpTwf4pNy3gCwz9LBHwhSTKSez796C6HlfBB2OlyFD/0tanqcZTqSfO6XX0Xn7nkRt2Wj6e1HUcp6sMLibcfheUfi7zsb3jROUPDN/ZvG6U52+NzF/AjUIuDpQlqsHN9gdw5uhLvkm5ktqQgrFdGQh+Ua8GMY=,iv:14muqZx02UBclOykZX2RRiINESIxKoHATA6QLDc5Epo=,tag:9nTWx+PSpflXe5WKOmdjbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
