apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
stringData:
    values.yaml: ENC[AES256_GCM,data:rI0qXmC8X5pI2SJ+kh4A0uX4f5a/XST5gL316SnVAW+l6gqxTtOVoNZTgCI3pOlGfwNrloKJvBEMdOBSkMOLPqILsRsyuoFNluv6kV78a0O7OUYyrbMWTNqPa9S1NzlNOSsZgvlmaU1B52xvatSOB8/fJRAYJOcdbiXJmsPuG6iFeIYYCA6eNdvOP5eA79nEtoEYFqeaGjAJ9ONNhq4XrxUWY7rCIsFAMYBG26YRmkQnibgLSmBD5ntMKytQnq/KRJMSj3nN/Cm3mrFOxSefPSXMvCPkI08nI5EiFwCJ4i1nTg1bTv2Ky6lVDxaMnaTRgxM6wCfLdg==,iv:QdVaxOx3lNIbUHGgqm3saDZTeR6/1gsqrZLy4no3HNY=,tag:9xFj6sK1KbJLHEBfRTrz2g==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHMwTmJHTFlBMEJ5blZm
            V0w3NlBKdkRyb1UyeHc1bzBGT2htU2dGcVcwCnFwLzVqQkpjMlBGeDMxcjk5ZThQ
            OXRhYUJOb1BuUHZuL2xYYWNzMXY3UmcKLS0tIHZNKzk5MnNvVDlrVUlxbWhETFpS
            UExXUng0T3UxWUY2SXd5ZXdCcXpacDAK9zQIh28Mko2aV5Yxl8feK2Sbmf5xe7/O
            NKiB3i8cVoFc38Hnd0SKYfMpTToOZSNTDt/Mz9FKhmrV5YZGHJ2PRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T20:39:55Z"
    mac: ENC[AES256_GCM,data:tPvCw3xfPWV3vXKUt/Kfs67T6LJqr8x+qvp09ynSFTPR/I2//h9t594sUI3vTsPIiI8sgpLPGGSZOR5WEp8PS9uYaBckI4+0QD/M2gNnOnfkNokO8q/BoBEUnFUbasn7+zTcEvUS0K/K/ll2EMwhgYlHuZFf0S5ylBQ1kgxLsqs=,iv:uD1orOwwHuDNuMB1UdiYtXSPX+btHPIVPAS8E2LOUiY=,tag:U2yBU1xxGwiMPIZ+x9bH4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
