apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-nextcloud-secret
  namespace: nextcloud
spec:
  secretName: nextcloud-secret
  organizationId: "effc79b3-9414-44ef-b833-b2ca0100595e"
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - secretKeyName: NEXTCLOUD_ADMIN_PASSWORD
      bwSecretId: "44a3b876-0ae0-4f30-a870-b3690165b5c3"
    - secretKeyName: POSTGRES_PASSWORD
      bwSecretId: "67554cdd-68da-4e62-bdf6-b3600147f651"
