kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi