---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: traefik
  interval: 1h
  values:
    deployment:
          replicas: 1
    service:
      type: LoadBalancer
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 443
        exposedPort: 443
    tlsStore:
      default:
        defaultCertificate:
          secretName: sluxcloud-wildcard-cert
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    
    additionalArguments:
      # Increase timeouts for large uploads
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=600s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=600s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=600s"
      - "--entryPoints.websecure.transport.lifeCycle.requestAcceptGraceTimeout=60s"
      - "--entryPoints.websecure.transport.lifeCycle.graceTimeOut=60s"
      
      # Optionally disable buffering (useful for streaming uploads)
      - "--serverstransport.forwardingTimeouts.dialTimeout=60s"
      - "--serverstransport.forwardingTimeouts.responseHeaderTimeout=600s"

      - "--providers.kubernetescrd.allowCrossNamespace=true"