apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_USERNAME: "{{ .DB_USERNAME }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_DATABASE_NAME: "{{ .DB_DATABASE_NAME }}"
        DB_HOSTNAME: "{{ .DB_HOSTNAME }}"
        DB_PORT: "{{ .DB_PORT }}"
  dataFrom:
    - extract:
        key: immich