---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: "k8s-nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
spec:
  storageClassName: "k8s-nfs-fast"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
