apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect # A descriptive name for your middleware
  namespace: default   # The namespace of your application
spec:
  redirectScheme:
    scheme: https   # The scheme to redirect to
    permanent: true # Issues a 301 permanent redirect response

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect # A descriptive name for your middleware
  namespace: traefik   # The namespace of your application
spec:
  redirectScheme:
    scheme: https   # The scheme to redirect to
    permanent: true # Issues a 301 permanent redirect response