apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres18
  namespace: postgres-cluster
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1

  storage:
    size: 50Gi
    storageClass: nfs-subdir-external-provisioner

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"