---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        prowlarr__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
    - extract:
        key: arr-stack