---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: si-discord
              href: https://discord.com
    - Git:
        - home-ops:
            - icon: si-github
              href: https://github.com/Slux567/homelab
    - Media:
        - YouTube:
            - icon: si-youtube
              href: https://youtube.com/feed/subscriptions
    - Reading:
        - Hacker News:
            - icon: si-ycombinator
              href: https://news.ycombinator.com/
        - Tildes:
            - icon: mdi-forum
              href: https://tildes.net/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  services.yaml: |
    - Infrastructure:
        - Unifi:
            icon: unifi.png
            href: https://192.168.1.254/
            description: Unifi Controller
            widget:
              type: unifi
              url: https://192.168.1.254/
              key: "{{HOMEPAGE_VAR_UNIFI_API_KEY}}"
  settings.yaml: |
    title: Russell
    headerStyle: clean
    layout:
      Infrastructure:
        style: row
        columns: 2
      Media:
        style: row
        columns: 3
      Selfhosted:
        style: row
        columns: 4
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
          hour12: false
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true