apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secrets
    creationPolicy: Owner
    template:
      data:
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_SEERR_API_KEY: "{{ .SEERR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_NZBGET_USERNAME: "{{ .NZBGET_USERNAME }}"
        HOMEPAGE_VAR_NZBGET_PASSWORD: "{{ .NZBGET_PASSWORD }}"

        HOMEPAGE_VAR_SYNCTHING_API_KEY: "{{ .SYNCTHING_API_KEY }}"

        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_TOKEN }}"
  dataFrom:
    - extract:
        key: arr-stack
    - extract:
        key: homepage