---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: homepage
  namespace: selfhosted
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: homepage
  egress:
    - toEntities:
        - kube-apiserver
        - cluster