apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: homepage-allow-ingress-from-media
spec:
  description: "Allow ingress to Nextcloud from Homepage pod"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: homepage
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: media