apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    client_secret: ENC[AES256_GCM,data:l+x24D9vRru9jNb0SG8S+8iH57yGzysQrSFNe3v14HHBoGGDUaFFc6w1KzkNoJMIf5ND08aPr+92RUaRWDJL0VyG5QNbSO3VbERhvAHEVlXlXI52XmwmJ85dn2eEkYrqna+ipKYC5HVLS6rvsSUuUWKHtmrDlpEzH2BFO6YejvU=,iv:wNG4myJe7uVjviwXANEhoOQQJlJxdwSQ96dXPEQY+68=,tag:1iBbSdKvp9zDBNlavIok6A==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSjlYbllGb2dpUFdSNTdh
            SmVDT3lGSmdST3ZpWnN4TnVJSFhHVTJlSEFVCmMrSHZqL3l2MjljYTJlZytZUUIz
            cWFza1pySFhSTFB5MHBHK3JWbXE1TUEKLS0tIGhaUFBtTFEyRlpuWUlKYnN2TEVZ
            UVllNjBUV2ZjNG5Bd3ZoV1BaRWhlTXcKX09tCe9/0vbJtGnz10DKxrJxMsprbh7L
            Q6HeY0O069dHnUhG5C3y3twMBazeId02v7QpC6gNDDuJGCuBigwACw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:52:52Z"
    mac: ENC[AES256_GCM,data:dFQ7zOm10+eyIpZoQVh04gsYtBnLqr1qWiXObxd3/S37MEMrGxDPEqDq4tDL9EhGkuCdtiX1BOBBSe2gJoPfNMo60AWoTz3LMpbecgZDNeC+QQsQudGEfeZayjYd5JcRoz9EVn6DJla0Hw9db1VVUmn7dEY6zNoLiiDRG3bUT+4=,iv:gyS8ZDNIKR4bvYAYAVwfA6J7z/PaqbXE+EZO1mZ5QKM=,tag:mUzMUTP4+O+m47LOc9U6nA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
