apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    values.yaml: ENC[AES256_GCM,data:izFpjvS8zb+QdIOVl8v97L2WEBIOeJ+x+kiA0FBF+7TwHeu5UcXD1Ft375yesGfV8W2sJljXTAPx/GxMCHvNizpvBQZENNDQRT/HqTOBkm+8S6ruoL/B0RWOLZmRmyAFg9KtrZejUeIynbkr6907nABgHfT9Qp4Inj7+RzpSOw/7byLMEr4M6BexA+CVB57LH/3TEy8sqnv+04LrYwBXC4/L0ytR/gvKoZUOEqKXaAn4MlrM0DIiUOnnT/crT59jzDZMf1+ej4vi32j/wG8MDC4Aiw7cWLItmsoq0aRwNvVsuND0NHy026uFONE1dtssHnqToSeu7Ospx4NtnL6VrziI76477qITPGlmTLMYZgHoP3CYqJyQzzD0yU+XZI1ptP6dGQGNTkY1/bKFfj869TJj5rM0vm0Rn0KddaOTnpDQcJtWKYXEICXt2/qjFaeHcNjlu32RoO5A2qbeUMvKgKa4VAKqlbMbtZEUtSta3qYVYefYnq+AFSmrlTm1gKV6NmeWDRyMWJ6T1RF/xyUdRLBYP2gQGYNeG2v3SY72wpIysRzpAhF8KA8HPrq1iH5jZVuTvpHTGnZZbMtMXGQ8brh37T4+KAIpjMp1D49nyd6EBYEJgNpvHboQbYAI6UBufUW1B7WCVl2Hkp9v9JyxydtdnyVlHgGmrTgqIb5O6pK0Y24h+yyjqClqN8ibdc/m8XvezQYyOCxkikYt5XTTE1RxYVOAuI/JNxluiMnopAGedIMc+gPd2dSi6FjWWY60HDlS9G8+xVomx3CnKuflFOVBMh4d1I83atGeMJlRmSBkE+OeTWhcSaORjBPHf2bWIICZDVk5hPoAU2BJPfvppOjuZpEic7Fm2fzUpd6pAt72Zv8DAqUs2MJ2I7vMFBQxLK1gL4Pao2yp+sw/OtiAmJvFTlNrfKrDUG+1ahkFpsgbCjyDBzkB6s2LbnwfiwE2Nn6FPJHiUSOuyR87vzh6vlScuKW4cOLf5/r6If0xOVhYOajChSZ1//Ty/kgcYBfe8dK2Z+g=,iv:Mxsi9sWjsN9Bf9f8TOfuHv/O2aOC3FvGg043oqz0Zxc=,tag:6ZB8XXEaxa8bvn+/7TpyNQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFczZJcGNYSExOUDJGaGs5
            T2QvU1JuNjdCOUtrQi9ZZ0JrbFBUdXpQRERrCjFzK0R2SE1SNUY4U1daeFNXY0Fq
            aGNGQ1UzK1kzbHdJb0Rsc0JPOEQ5SFkKLS0tIDJyNms3YXlJNVpTRGdqeURQYUgx
            TzRUQzY1Mms4U1RmY1JkQXpzazVsWGcKhXlmZpjqe9/EGyqLGgW9cYYrBCu7eyZr
            f9rBqoGXjjFhdjGjCQ48p2ZTBXafIl+db6V+vhaMES1QcHDaC0Ml8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T10:15:54Z"
    mac: ENC[AES256_GCM,data:/peS7qROF854DRKyTsfLxCtsblzfkqYyWlLY1fLkZ1RHHB1LImfvwmQwhMP5GQPdEuYbvHGiAxcpU+KH9S99hLhaORtCuXIrJSvr4m6NmbHz0h0yhRYpfQinq/t6xQBuo002FS4IHlY2Z8dwoU2aO61PsSQ3XI+Ct38QuKuy8cE=,iv:qEkyWVD1TTYK29MEG74XKTAgl3/kCPUd2q3LcCFpNwQ=,tag:B4Dx67rJvhnT0Amn8adEhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
