---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 80.14.4
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
    namespace: flux-system
  interval: 1h
  values:

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi

    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.${SECRET_DOMAIN}
      prometheusSpec:
        externalUrl: https://prometheus.${SECRET_DOMAIN}
        retention: 14d
        retentionSize: 50GB
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 4Gi
        storageSpec: {} # disable dynamic PVC creation
        volumes:
          - name: prometheus-data
            persistentVolumeClaim:
              claimName: prometheus-data-pvc
        volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus

    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.${SECRET_DOMAIN}
      env:
        GF_SERVER_ROOT_URL: https://grafana.${SECRET_DOMAIN}
      persistence:
        enabled: true
        existingClaim: grafana-data-pvc
