apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-authentik-secret
  namespace: authentik
spec:
  secretName: authentik-secret
  organizationId: "effc79b3-9414-44ef-b833-b2ca0100595e"
  authToken:
    secretName: bw-auth-token
    secretKey: token

  map:
    - secretKeyName: AUTHENTIK_SECRET_KEY
      bwSecretId: "c039eb64-f64a-4352-ac84-b35c01240767"
    - secretKeyName: AUTHENTIK_POSTGRESQL__PASSWORD
      bwSecretId: "539ffc86-a672-4399-8cf7-b35c012c00e8"
