machine:
  network:
    interfaces:
      - interface: enp2s0
        dhcp: true
  install:
    disk: /dev/nvme0n1
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: asgard
auto: off