---
apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-intra-namespace-security
  namespace: security
spec:
  description: "Allow all pods in this namespace to talk to each other"
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}