apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: security-namespace-policy
  namespace: security
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
      - kube-apiserver
      - host
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchLabels:
            gateway.networking.k8s.io/gateway-name: internal
            io.kubernetes.pod.namespace: envoy-gateway