apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-values
  namespace: nextcloud
data:
  values.yaml: |

    image:
      repository: nextcloud
      flavor: apache
      tag: latest
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      className: traefik
      path: /
      pathType: Prefix
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
  
    nextcloud:
      host: next.sluxcloud.com
      username: admin
      password: changeme
      update: 0
      containerPort: 80
      datadir: /var/www/html/data
      trustedDomains: [next.sluxcloud.com]
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: false

    internalDatabase:
      enabled: false

persistence:
  enabled: true
  existingClaim: nextcloud-app-pvc
  accessMode: ReadWriteOnce
  size: 20Gi

  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data-pvc
    accessMode: ReadWriteOnce
    size: 1000Gi


readinessProbe:
  enabled: false

livenessProbe:
  enabled: false

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 300
  successThreshold: 1

   
