apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
stringData:
    values.yaml: ENC[AES256_GCM,data:rKFPibut04+GZUuZuM/49t/SFpDFg90pW7pZOmpftt4HefwDdAhZk7aLDyz6dVWZxbA9UF3v649txYhRyMQeXFZMf9r6up6D2jyqYhFct9HHu006C79rcw5RXrCj6QGGaJ0OMWSVgzl8hTSvsBuK1Q63xFEZtuD3qyhE38BfqkNOXPHd+D9CrghQf6w2rZe1kHywbLfZ/FC3T2M6JW6Ltlyn4dVttPGoSN24AX+GIXfJnoO2bpKNG5MwgyRSZrxUKdmnzRUyk0BlgVhLcHM8gscW4IUUJEkK3NENDEmywetnwEg6mA==,iv:lCouGu21pL1AIRucI+mRHCUlajOpZ0DPnzhnJZfWf74=,tag:/0QBFCivPKnrg9e+z9nllA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUDZNMFlrVjBlNi8xR2FG
            cWd6SHVTdzg2aUJYZklUcFNZZENIZWphTmc4CjliSThmUmh6TGZFOTVsZ2k3NlBV
            T0FrZ1dHZXB3VU9ydlN0TWxKMXFFN3cKLS0tIC84dzJwa1BEU3k1elBsc0JQRWo0
            Q0ZsM0YxbCtjZi80UzBBRVZqRW1QS2MKuL1um8EwZ8MlGWoIpVCp1SyVi49i88WJ
            am6MVVuVuLzSx4JdRUxtUwkdldKm4QZtLm79rMHtajH7Du+JOeoYww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T20:30:21Z"
    mac: ENC[AES256_GCM,data:SQxgK3PEdeilCFZpx24lnVF3s3PAyg6cW9mOXignZ7yOKbaIfnt/lcvJ8QzcCakpKOy7RpWeR+6OD5yFP10HalRmLmlCSTRIQ5wVp8FN5tRICODBt/kZXGI+sukn/jggwE0llFnf43KGQ5lDt9IaU29snCVZLCRHBj3PfZ1yFeM=,iv:TvQuWsBhthYOzzUYs4Nocf0Jzl3TWJxMDy36/rLon3A=,tag:b1X46tbvw4d0zJZwq4OLdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
