apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
stringData:
    values.yaml: ENC[AES256_GCM,data:iFuBIGpgX1X/xUX0/J4HuVrb3wD7o0sVChfce3OOI4pCDeET4rwX2kle7efb/BXW5SGY6D3O2eS+QkShCXT+a6XMAFfD+INlEwKtUyHHLw8zkxg/V2uK2ifpKwO2oj1z2/AYYa5RoHnOvLMKosg1dGc2R28EQI1t62drxbBhNL0KzZ4zko1/5fwq3YOO8Xz+BExNnuveew/eq41URMOSAmQyQfFkkTXsbbfeI8NdvVauyFrIswC7ybNCNiTiPtr2w1Akozri/n6Nv1n2hFWdSpl6mGv06WWl4XSkkBcsuz8c7GcSqSn3uTMi8s4HLU6KyZL3ATnHVAc=,iv:Ws3ssRSEMesZGOYHzP6JKcmlrlyByZTwMuxYaE/rsaM=,tag:LwD2PTTTKWXWhvMYdzpPNQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU2xFZkhpMjBQeXlRYkNR
            czRDRUxxWWNLM3g1cDNodGU4R0VabVJKSUFZClpvUUZRbUhtU3JyWDFsK21jQXVN
            d3VlUldvK2s4Mmk0MXpVWkRHejJaZDQKLS0tIFZqVGJveHhRckl0Q1JQeEFNdi9U
            YmJ4OVQxQTNKeXcySC9kWDRxeE5RS3MKjpds5Iw56zgyyeKEd/t4IMUql2GcmWce
            R8qrphLgW7rmXl+M36ESqAux9ptnrHSclMJRHfqlAbYyKum2TbV4qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T18:37:00Z"
    mac: ENC[AES256_GCM,data:u5Z9aXmMHd0So3mrPpwvmZFLw+UChVqm7NqILjBujQoPCZ4XagDWTclwtyFTAcAikHhK8u2JMD8MHnP50QbsUxPK0fsxV41TDr/2llYkopH2Mhr9L4zm3SXTcpWJPw53AYY12Gv5BrI1yh0hNhVJSMSCW7R/F85xVAwzYWZLk4M=,iv:fR1bWO8ntR9EcGH61MdUXoQjszYL90eOq4jCgV1fikM=,tag:K58JU+3LfkKr3ie13s9cuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
