apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-homepage-to-nextcloud
  namespace: selfhosted
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: nextcloud

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: homepage
---