---
- name: Download oh-my-posh
  hosts: all
  become: true
  vars:
    target_user: "{{ 'pi' if inventory_hostname == 'pi' else 'slux' }}"
    target_home: "/home/{{ target_user }}"

  tasks:
    - name: Ensure unzip is installed
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true

    - name: Download/install oh-my-posh
      become_user: "{{target_user}}"
      ansible.builtin.shell: "curl -s https://ohmyposh.dev/install.sh | bash -s"

    - name: Add Oh My Posh init block to .bashrc
      become_user: "{{target_user}}"
      ansible.builtin.blockinfile:
        path: "{{ target_home }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: Oh My Posh"
        block: |
          # Oh My Posh
          export PATH=$PATH:{{ target_home }}/.local/bin
          eval "$(oh-my-posh init bash --config ./.cache/oh-my-posh/themes/agnosterplus.omp.json)"

    - name: Ensure .bashrc ownership is correct
      become: true
      ansible.builtin.file:
        path: "{{ target_home }}/.bashrc"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'


