---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: ${NAS_IP}
    path: /mnt/tank/media/bazarr-config
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: bazarr-config

