# roles/docker_compose_handlers/handlers/main.yml

- name: Restart portainer
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/portainer/
    state: restarted

- name: Restart traefik
  become: true
  community.docker.docker_compose_v2:
    project_src: /opt/traefik/
    state: restarted
