apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-secrets
    namespace: monitoring
stringData:
    values.yaml: ENC[AES256_GCM,data:WZwKDhuEr+LNx7/I+OwA8EpIwIx25udwFbmojMmanF2dbWMqyZLu68K5mDu3yoEEwiZP9mPPpnPKtqLmVvHr9+swyERdSf6INbAbGbn0fi3b80s3uRSFBJmp4KoXRe9FrHRdISIxiV9sLFY=,iv:VAWosrZey2jDIp1wm1pcC2mr0cpcp1evL3PX0FyxmCc=,tag:NeGNjacQEjkP5wU+X7yuEQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNjVzcDRFTUJlSlUzNHJM
            RDcvamtGb2dkOEpyelJ2VGdDWjFKSG9oOTI0CmE4WWhvOUdybi8zNkVIN3pSU3Zw
            K241SERtb1JRWi9VbHRnWUlFSjY2RzgKLS0tIFZuRmtxRGVDUEFnSjl3eUlMenpM
            OFZrUVhjT1NnTmZKc3h5STZNcnFxK1kK8xVkTv4RHFxFsi+SOOhyC0Z3/0Q1d6Qd
            MQSzKR5XOBtIC2Hc4gYjXsIFLz2yXjIEkQ8x58Df31eptu6cKdf2Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T00:18:00Z"
    mac: ENC[AES256_GCM,data:ilMuHWovRPRAnWYra9l3it8RWfJ65XvrEXHk8pLgTFfv2Kja6pZpvICHOPJPwDKsIcTD0sBRe0gi9uiaBu/sP7GZ/1g1VpUKxDwhSau2LZOonCNGQ5wL7F4EXyYNIVIR9mXSZ/lkUaJbSNWk5xBURte6fhbkSyJux+jjjQWH8Sg=,iv:lT3xD83YSKd7Hx6QSXoLK0N5hWXxn3k5O2c9R7yUmnE=,tag:WA8ZyJvlF/zS7ZtMGA3/DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
