apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-secrets
    namespace: monitoring
stringData:
    values.yaml: ENC[AES256_GCM,data:jUNaROD9ChL/JYKoiaX0la6fqfpoPrOdFbrfYddsARzTsCqI/H2WmlS3cCWQQOMrWswI96BtOaOnCPGMezfp4Qt+N7Q6jFZAKNfBv5m+dYQXUa8fji5VF7GbMfSIKFO01z7YBichBB0eD1Q=,iv:f6LLVUO7Gem+BUm1o8Q14PrAQcq0i1+8btNwazM6Yxc=,tag:AtceBSElZiuX0RInpG9pqg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVFnMVJZM1crWUpvUG5q
            YWZKa2hueXAyOTIrMzBMQzBCcjMvUDVRRmprCjc5bzlOa21nd3hGd1JxTitWTGZk
            ZnplL3lvTHg0NGZ0QVBldVRoc2t3K2sKLS0tIGdtdk56V3A0MGMyYU5uNWxnU0Yx
            SUxXS016MWYyUjdXbVZqM1BLRDhHeTAKZlUOkx63bLfKjNRFKFb4DwIcD1nobWQw
            3Xom/qo+2bSh5Qa8OhmKm3T/gJhNoynrwDCaL1jULTQNrIcVze+JfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T23:36:53Z"
    mac: ENC[AES256_GCM,data:Kdd8cteZZX7AOVAi504ccpNdsrRJPS+Mw3pSpaNl8WKkhI8ILzSIRgNqnhKoIIJffWQOFO/oEyo0hoymv5y3JIXbrHVnK2nwhcOY34xhtYCqxxhBkwcDlPSXS93ku36LE9RxAIuCpCwmASYTyetBSN2gA5YCB2almVfGn+y5hek=,iv:iaocHuRk1/+XIGXkGqSLlva4Tx67iiaMZuA6rF5QZdk=,tag:adUOvcK/kDAVKhsNGzUz/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
