apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-secrets
    namespace: monitoring
stringData:
    values.yaml: ENC[AES256_GCM,data:tOAJwatCNx15zVqm09vWQu8ZNPUuvqmqwivaYNaw4xnqBxo/QkU47DJLEYfajxhnpLVbNpTH+LfJEwZVCpe7B3Xfkt4ETLjvAiiUCmolG/x/BbiS/G2DGfKBAkbPdNi3nBzJzZy7CyzIw3nd,iv:iX4RD1OEkXMSQQNEppjo4EM5oeYZsvN8tKf3P7HZFus=,tag:oJ0OddV79oEeAngl8o938A==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbHRMclZkM0RkNVpDQ0N0
            NncrWmJuRVBJWG1Yd1lld3UzcXlZbTBkWEZBCnJGODV6cloxQkZzM2FsUVZPVmRH
            VGE2cC9NSEorYWw5RVpucGVYK2V2UDAKLS0tIHB3TEczVkdTcGk2Q3ZRaHk5S1ZD
            V29RbEliQ3RSNFpvdHlEcUNEcGJ3WFEKpR2JkWf0+4DfObyyYwCBtRebBJ3IzYvp
            xJejJ6fwb07OFtu8rTzcjrWkg8cBF9g7JdwFKbcQA9AuX8hDyG/bWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T00:14:10Z"
    mac: ENC[AES256_GCM,data:beopvBhcMoXdD1in8U3h7qhDaOPE9eBYwkQcT0ai2QR+s43IPYSQyGscoIb4g5bdh7hgKHmX3wDaTGFoy3H+W6UAhCTLSlUh/E82IlFdT5IwtPeAvkvccpiVsqq3smvaAc198Y5XaiPikmbkUIm9dMvwffl4MzYxJbcafzPlwag=,iv:84mPi0Li1ebpAQGDeTcqW5XpgqysOhvorC2eEjCI59U=,tag:6ZyYLo/R74TjKzqTydf15g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
