apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
data:
    values.yaml: ENC[AES256_GCM,data:n6aAxb717xsem93p5H9BTZu3WwQHrO9Ag7sVUb1NVe75v7JlbZiG23C1MMTjWGHHWQxOJB64lAIIljj8wi/T1XkZytkZI+m2tIBw43oaR4CvNW3RkhrfO0Ffw6rZpWRmKOBP9QjbRA8HCa6lFnJMk3m3tgjsN6AXuf0cF/sMnIF+lldD/+oE7pVvjwqtjiBlXxH74l1veu5dH9vXV9F2tiozsqr+of/tBOy46wlhBOmkOs1Y0ImmdSKW8jTD3/4aBcg/bEW2gMr/UgLwv+tGsKrpN1OnEPF1hJ9KR5SvrNBLbUubwA==,iv:2z5QstX786QsVll4O0/lwC6kBVuHw/0pkQZrk8cnwwo=,tag:yq3ng4cdma2Ux5FRq6PkJA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYUxQS1dHUlIxaGgrMmt5
            blN2STNISWRZMlJEUjArdmdYS25IK21sU0hzCnBibllQQldYUnBEeTlpaEd1aUhs
            cDRMTm5IWmhFcm9QdU5aVVYyTjd3UG8KLS0tIENiM1NmeEJFQ1lDdFR6d3FQWWRn
            WkdHZmxFYWJCcENQMnRPR0l5cEw1Q2cKbel4ymcdiZK6712CPdABUuR9i5MORDBf
            oNdXYkoL+SotnzqwYn+VojJgH4uGF2KmEak1GLgw0yB+TUP0vG4oGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T20:17:36Z"
    mac: ENC[AES256_GCM,data:c4xPy9MLVCsdQzzQGFmS0eWNgtj1/GnbO1bZ3GdfJW1iwThvWzUi+3BEAtlfnlUladFIEhqamwhv4kY8zbwyqWJLtgjAl1XFKYxl5gCRk96RbjwHiPuArDQe/Ua+VTZbUsOOosa+WwRenjKUM5XzGw2stIAb5B/jie6AZQ4sMNI=,iv:X/Wqeh/7MQDaeM54xTkQID8HIBGxLsHq9sRl5stA6NM=,tag:dgugP4rUwNfvxMTAO6ffQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
