---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: filebrowser-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server:
            cacheDir: /home/filebrowser/data/tmp
            sources:
              - path: /data
                name: "Data"
                config:
                  defaultEnabled: true
              - path: /media
                name: "Media"
                config:
                  defaultEnabled: true
          auth:
            methods:
              password:
                enabled: false
              oidc:
                enabled: true
                scopes: "email openid profile groups"
                clientId: "{{ .OIDC_CLIENT_ID }}"
                clientSecret: "{{ .OIDC_CLIENT_SECRET }}"
                issuerUrl: "{{ .OIDC_ISSUER_URL }}"
                adminGroup: "Admin"
  dataFrom:
    - extract:
        key: filebrowser
