apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser
spec:
  storageClassName: "k8s-nfs-fast"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-data
spec:
  capacity:
    storage: 4T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_IP}
    path: /mnt/tank/data
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: filebrowser-data
    namespace: selfhosted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4T
  volumeName: filebrowser-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-media
spec:
  capacity:
    storage: 5T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_IP}
    path: /mnt/tank/media/media-storage
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: filebrowser-media
    namespace: selfhosted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5T
  volumeName: filebrowser-media
