apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://vault.bitwarden.com
      organizationID: "your-org-id"
      auth:
        secretRef:
          credentials:
            name: bw-access-token
            key: token
            namespace: external-secrets  # The token lives here