apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - community-charts.yaml
  - immich-charts.yaml
  - grafana-charts.yaml
  - traefik-chart.yaml
  - prometheus-community.yaml
  - authentik-chart.yaml
  - alertmanager-ntfy.yaml
  - bjw-s.yaml
  - cnpg.yaml