---
originRequest:
  originServerName: "external.${DOMAIN_01}"

ingress:
  - hostname: "${DOMAIN_01}"
    service: http://external.envoy-gateway.svc.cluster.local
  - hostname: "*.${DOMAIN_01}"
    service: http://external.envoy-gateway.svc.cluster.local
  - service: http_status:404