---
originRequest:
  originServerName: "external.${DOMAIN_01}"

ingress:
  - hostname: "${DOMAIN_01}"
    service: &svc https://external.envoy-gateway.svc.cluster.local
  - hostname: "*.${DOMAIN_01}"
    service: *svc
  - service: http_status:404