---
originRequest:
  noTLSVerify: true

ingress:
  - hostname: "${DOMAIN_01}"
    service: https://external.envoy-gateway.svc.cluster.local
  - hostname: "*.${DOMAIN_01}"
    service: https://external.envoy-gateway.svc.cluster.local
  - service: http_status:404