apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-observability-policy
  namespace: observability
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
      - kube-apiserver
      - host
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway
            gateway.networking.k8s.io/gateway-name: internal