apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: plex-allow-homenetwork
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: plex
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.10.0/24
    ports:
    - protocol: TCP
      port: 32400