---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: plex
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: plex
  ingress:
    - fromCIDRSet:
        - cidr: 192.168.10.0/24
        - cidr: 192.168.4.0/24