---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: plex
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: plex
  ingress:
    - fromCIDRSet:
        - cidr: 192.168.10.0/24
  egress:
    - toEntities:
        - kube-apiserver
        - cluster
    - toCIDRSet:
        - cidr: 192.168.1.254/32
        - cidr: 10.0.40.50/32