---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.50
    path: /mnt/tank/monitoring/ntfy
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data-pvc
  namespace: monitoring
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: ntfy-data-pv

