apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN_01: ENC[AES256_GCM,data:Wxq/wDF48A1d4ZRjhQ==,iv:hiKx4Ai8gst+T6CdVRWHBkbZIV3wPHnFj7I5xUlW17g=,tag:tGdgQTAwDBQ/JrDw3lW56g==,type:str]
    NAS_IP: ENC[AES256_GCM,data:r5uveWOgmKCQBw==,iv:rh+UHL3YNhW8eS8S19hbNg+KetWc/vFR54B3pswDDOI=,tag:DOPZFuo9FgZ3gzt+62P8ew==,type:str]
    LB_IP_TRAEFIK_INGRESS_INTERNAL: ENC[AES256_GCM,data:hH0vbuSGuSUCVQ8=,iv:hOzJjzmnrZy9hCBLGvf11enilTVjWn/UAylvlcz3dXA=,tag:lWgesHu73DVhzExPd/IGqQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTnppM29uU3MzRkVEdmFT
            d2VDZmQ1ZHNlNW80MUNPc3BOWXN1Y1QyOWo0CmlsOFlxZWRwb3VBT0dNUzRVT3du
            VGFpb21sYVZmYjNlSSt0aXhTa2ptNXMKLS0tIGZCRFJRTmNUUVhLaEVGT3pyejRN
            L3R0bk5Zam1XM0RXeDhrU1loRjFGbmMKJmdX5vQ4q164kc2+iWlMS/vxOXdS5VYz
            E/cIBA+EinrMpZxm/lYbMRqTXLy+apG/YFGnr16K1jnK5WckNabUGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:00:34Z"
    mac: ENC[AES256_GCM,data:k6Dfc4WaQeUaZ2EgAlWf/PtHqEjbDDMChWL0ias1i+Nfng8ny19Dp5T3q8V1qQgtsO5QmSFg7hIajtiF5zWpMBy7VCnVFW/6lJQ1yTaRfGyCavDrpnqsAKghwawRqJVfwN4aMq7otRrXNhUeKc4IzaYWyMoC+ggjdURuU1ekIYo=,iv:UHx8wC2+xfAdHiJwA8eYCGAh5C2rhCZAORjkj1YiFuY=,tag:btrsQvR2qFHR7xpOhk0KFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
