apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    DOMAIN_01: ENC[AES256_GCM,data:dUOZsVJln6e/tEo7cg==,iv:udUj7aVAVlGLy41YxKwgD1Gm7OwOoCGUjCO+XM2PC9c=,tag:DwAVRLL8ydpHYcFJQEOWug==,type:str]
    NAS_IP: ENC[AES256_GCM,data:Rd+VIKHbAJIFXw==,iv:EK4vRGffB4CL7d+1zEul9HLFAxGOUHF6STnjuxwU9gI=,tag:uoWkiHX6+vGJxNWRAzRq4g==,type:str]
    LB_IP_TRAEFIK_INGRESS_INTERNAL: ENC[AES256_GCM,data:ZH3p6HkukOfmZm0=,iv:3LyGHkUtcFlo474tNz115KP+DMWZj1v7W/wt1lRG/wI=,tag:bLlK+WgfJYqrcogpkqPaVQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVRZZDdodmt6YUI4S25L
            ZExHZ2VBN2Q4VjZNT3dqN3dMek1FNENYd1FFClkxMEJvL3FSc0wwMUg0TnhIVFJS
            Q1A4UjJxZlNXcUZPR0MyR1FCUDhYK0EKLS0tIEE4Y0dzQ0tvb1Jpd1RnMVM4L2Ns
            TW14d1o0cmxyYlFUSUtXWmNGcnl0amcKF7dxQopfNZrNyZufY14BDcrqLULHNBPs
            hiuuYqkP8Z1UKR6nYwHpz7EYuCbvqTOnbFPVyDIBlo8wWeYtrHE2nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T22:16:46Z"
    mac: ENC[AES256_GCM,data:quHU7tD03VYwbBWAzOZ038lwybJEN+eQcDpm3XfWN39/6dxkVUhmw50dQw8BxK0Ykx2AqOFTWkGVJiekqEWUA9VL40iCjAiiUO5O0GUdZyKf3DyWxMbsKuz5KkdwfuyuUtSs97Z6FyK3SQ/xKnhszaiAWUr4/WS7I6Q+1doItRY=,iv:q7f1E8yLfRWuzsZ4iPBsd16LZRFHi9rufOzDNxw9j7k=,tag:bW+rVh5pTZvUmVFwiHNw8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
