apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slux-solutions-wildcard
  namespace: default # Pas dit aan wanneer je het certificaat beschikbaar wilt in andere namespaces
spec:
  secretName: slux-solutions-wildcard-cert
  issuerRef:
    name: letsencrypt-prod-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - "slux-solutions.com"
  - "*.slux-solutions.com"