apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          main:
            image:
              repository: ghcr.io/gtsteffaniak/filebrowser
              tag: 1.0.3-stable
            envFrom:
              - secretRef:
                  name: filebrowser-secret
            env:
              FILEBROWSER_DISABLE_AUTOMATIC_BACKUP: true
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 1Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        className: traefik
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: files.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix

    persistence:
      files:
        existingClaim: filebrowser-files-pvc
        globalMounts:
          - path: /files
      config:
        type: configMap
        name: filebrowser
        globalMounts:
          - path: /home/filebrowser/config.yaml
            subPath: config.yaml
      database:
        existingClaim: filebrowser-database-pvc
        globalMounts:
          - path: /home/filebrowser/database
    configMaps:
      config:
        data:
          config.yaml: |
            server:
              port: 80
              baseURL:  "/"
              externalUrl: "https://files.${SECRET_DOMAIN}"
              logging:
                - levels: "info|warning|error"
              database: /home/filebrowser/database/filebrowser.db
              sources:
                - name: Files
                  path: /files
                  config:
                    defaultEnabled: true
            auth:
              methods:
                noauth: false
                password:
                  enabled: false
                oidc:
                  enabled: true
                  issuerUrl: https://auth.${SECRET_DOMAIN}/application/o/filebrowser/
                  scopes: "email openid profile"
                  adminGroup: "authentik Admins"
                  createUser: true
