apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secret
    namespace: filebrowser
type: Opaque
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:1qaeOwILQpNMcbQTEm1l1pGQfpg2zHLHKlOQFjRj0go=,iv:5CiXWkhVoGcL0JZzIc2q0Yw4iDR8XhjHHjZ0p5yRkKA=,tag:0ZOvHvbIqK6ODovYFf2n1A==,type:str]
    FILEBROWSER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:RPCaCatD4Niwt6FFGjjD5pi96sKH1kXZ7HRwkXlAQdJDcVD5KwpggA==,iv:J80wUGhHv8wN7pNk+baXo29OgqSu2gqyfbtMIlCWUkU=,tag:Q4Nf3SCKlAmzI0ixVzjBPw==,type:str]
    FILEBROWSER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xF6i4vy0idxsxJD4WmcBF/c57zbrulLSVWXA08gXPiG/Qri9L/OP1S7jCG+EGQ+9XOxirqurHxlyNm82lXHQCijhLHyuk5+Ulb5PeLBcTV0WdKkSnwQnlelEtUvYaZLatCsUNu3GUryvOZIGcNDDf3iLHnYAXmC78giZISFvHE4=,iv:85ti9tyFgw9PgFIUT20QNlTv0zD6nzukCvywOXoHkVk=,tag:bVF/Cq9XrBt2IOrmjKt6wg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNy8xcWhjbEw1bzBMem16
            dzh5V1BINnBqRXdYeXpjRndrRXRMMG1CTWhZCnpCSUxOQVRWTTgvQUhhZVNpLzNQ
            a1dmbWJrVExuRDFuNlMzN3JIaE9DVkEKLS0tIFJNb1NyT1NneGZ6NjZjUkd0YXBj
            MDlEcytQRXpDQ1RObnJzLytKc0lpSGcKowb+IV6NQFTwpnqFTCir7F24i3qevjKP
            Xz0Lo7hqpUXaUKaG94DbeD3u+IncieUZOe0XqoP6YinB3+X3pk9igw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T23:38:21Z"
    mac: ENC[AES256_GCM,data:v2LowulQVtRUDf/WVHAc5J9pU7M3FAjBXE5DUK5zaSfHtvn9ivD+HPHOx22/iJoKJzWodmognkyGGfJFgy43hMEff38jx5px6kdaMuSUYpOw2OUArV1WyRtibtNeYYQyuLqy5jqZv/zKSWOzehcID4LraWj5TqZDYcIlUM5GCOA=,iv:XG+nb16KVWDDnwVN2vc9mKvvKS6tsuRjDhpARnCYkDo=,tag:iPJPSU/BFVDUrS1QF1IzgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
