apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-oidc-secret
    namespace: filebrowser
type: Opaque
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:cELpIJZR89Rji4q45LB7v+2HSIAJEakinzPiRlSnsUQ=,iv:AIyiee2i7gxD5RY9xX+aZgM7o5XQz06agUzJmlUfOJI=,tag:5Fgk1gwWVtcDH6YzC3PnlA==,type:str]
    FILEBROWSER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:ND1eKoU4F1vvqbKqSkY00zQNAkaxfALtksziJgXsTN5TksgJu8bpBQ==,iv:IJQ0Hr24oMK0bUNL8rJU+K4KtHlaNsilV3UO7weE3qo=,tag:knSl8DepS4XMlxFahWf8tw==,type:str]
    FILEBROWSER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:l8F25UA37gmLjZ8Onww6x1f60pWrpSSgb2KjIhaCzzxNEVp5cDbuwxwTfuxV64xHPFJGrub2pLy0jm+vnAxGnc3W84HUaaZcOhd7OeDBx0QPIequQW7kDyl9ge4RWC1V3+EKRApFNHlgRMmj0Bs67qdEXlvNbA0B+pitl1TqeEc=,iv:btDfRmhz0CVkDOEeOBFD6gD2OivGLlX8aF8mwuQuJ5s=,tag:/IVQMInwKIWT+3CqjjfYdQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ1J3TSsyQmNrVkNaTjF4
            TGdzTDNMRmNxZnYrZ2E5YmQ0OWM0cDZZMUZFCmVUeEdvVytxaWd0U1M0VGtQQTE4
            UkN3cWM1TVdydzVoVk95YitVaE5ocE0KLS0tIDlBYllBVG9VMCt5eU1vd3lCamJ6
            YVFsL01kY2JSaklYVElEdm0vdUpMS0EKZDEbchLJPTLNPmKiRuet0tquIXpjcaK9
            Z5bjWQIRlc59ZcRuhIrH1IYlRU4vnB3l7qeCvo9uGsJI61SOTt85bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T23:05:41Z"
    mac: ENC[AES256_GCM,data:giCZbGqUPQqTfWzSxucQgIR2m8aI/2z5wNthJjUbJv49T3BRJlGde+Mkr/31nLCevLj7IkFAuGPTQSLYDjDK3nV1HYBCVDzUHfqTdzpcCez5wBRvpwqXy+8y6IO2ZNcqd1sD4GT7o9hp3y9SYTCcZSu9x19MI28yM64DdakPG7A=,iv:u9G51IuZbniRkEWymRBK4QnxRIDhqryRgz+K1SNC5W0=,tag:DpxtQGyv0d7eDCfAUlFP9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
