apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secret
    namespace: filebrowser
type: Opaque
stringData:
    FILEBROWSER_ADMIN_PASSWORD: EKLpXjBL0qQxaLC0W37DBJqR4HCBihCS
    FILEBROWSER_OIDC_CLIENT_ID: zdjsIk1Qx7YXYmmBUaMzxS0koSCLV02XBUjD8rjw
    FILEBROWSER_OIDC_CLIENT_SECRET: j1Vksn7Z2VNRrXpflhhjoZNctVCdl1xUqceraMXZ8CdaztIb83EDpYdf1RQUNe4U9rkItCyCiQJEbJP56xtCgDAE7ftENE6mhCLxh41WjypGzhakOKW2hQTkxEmhjpma
