---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-database-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.50
    path: /mnt/tank/selfhosted/filebrowser/database
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database-pvc
  namespace: filebrowser
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: filebrowser-database-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebrowser-files-pv
spec:
  capacity:
    storage: 4000Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.40.50
    path: /mnt/tank/selfhosted/filebrowser/files
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-files-pvc
  namespace: filebrowser
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
  volumeName: filebrowser-files-pv