apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-grafana-oauth-secret
  namespace: monitoring
spec:
  secretName: grafana-oauth-secret
  organizationId: "effc79b3-9414-44ef-b833-b2ca0100595e"
  authToken:
    secretName: bw-auth-token
    secretKey: token

  map:
    - bwSecretId: "e3a96d3b-448f-4f8b-affe-b35a01478654"
      secretKeyName: client-id
    - bwSecretId: "10811716-fabd-4c97-b9c2-b35a01482173"
      secretKeyName: client-secret