apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: &key RENOVATE_GH_TOKEN
    remoteRef:
      key: *app
      property: *key