---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  interval: 5m
  chart:
    spec:
      chart: renovate
      version: 46.31.4
      sourceRef:
        kind: HelmRepository
        name: renovate
  values:
    cronjob:
      schedule: "* 6 * * *" # Run every day at 6am
    redis:
      enabled: true  
    renovate:
      config: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "platform": "github",
          "token": "${RENOVATE_TOKEN}",
          "repositories": ["Slux567/homelab"],
          "extends": ["config:recommended"],
          "ignorePaths": [
            "kubernetes/clusters/homelab/flux-system/**",
            "kubernetes/vaulted-apps/**"
          ],
          "enabledManagers": ["kubernetes", "flux"],
          "flux": {
            "fileMatch": ["kubernetes/.+\\.ya?ml$"]
          },
          "kubernetes": {
            "fileMatch": ["kubernetes/.+\\.ya?ml$"]
          },
          "dependencyDashboard": true,
          "branchConcurrentLimit": 10,
          "prConcurrentLimit": 10,
          "prHourlyLimit": 10,
          "baseBranchPatterns": ["main"],
          "automerge": false
        }
    persistence:
      cache:
        enabled: true
        storageClass: "k8s-nfs"
        storageSize: "512Mi"