---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  interval: 5m
  chart:
    spec:
      chart: renovate
      version: 46.73.0
      sourceRef:
        kind: HelmRepository
        name: renovate
  values:
    envFrom:
    - secretRef:
        name: renovate
    cronjob:
      schedule: "* 6 * * *" # Run every day at 6am
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: "0"
      jobTemplate:
        spec:
          ttlSecondsAfterFinished: 600
    redis:
      enabled: true  
    renovate:
      config: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "platform": "github",
          "repositories": ["Slux567/homelab"],
          "extends": [
            "config:recommended",
          ],
          "enabledManagers": ["flux"],
          "flux": {
            "fileMatch": ["kubernetes/.+\\.ya?ml$"]
          },
          "dependencyDashboard": true,

          "branchConcurrentLimit": 5,
          "prConcurrentLimit": 5,
          "prHourlyLimit": 5,

          "baseBranchPatterns": ["main"],

          "packageRules": [
            {
              description: "Auto-merge OCI Charts",
              matchDatasources: ["docker"],
              automerge: true,
              automergeType: "pr",
              matchUpdateTypes: ["minor", "patch"],
              ignoreTests: true,
            },
            {
              "description": "Do NOT auto-merge major updates",
              "matchUpdateTypes": ["major"],
              "automerge": false
            }
          ]
        }
    persistence:
      cache:
        enabled: true
        storageClass: "k8s-nfs"
        storageSize: "512Mi"