apiVersion: v1
kind: Secret
metadata:
    name: n8n-encryption-key
    namespace: n8n
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:sr4DCjDN/B+w0uZH7WSGbCdXT0rIAfY2xPVpI9wRGbw=,iv:jUePIVNvhAIcdEncDSJzuOCBAaDltY9xIorWcjroIog=,tag:qz0eaUVIXuhj8kIj+5G1Hw==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNC9xbVYzbWhHQ2RIOEZL
            WWMvWXpSdUlEblMrMUN4Ym5DdHpDMG8xdjJvCmdTbmRsZTdiSUQyMnJ2Z2RrUEhE
            MGdxM0ZkR1JIbUM4YmFDODU0MnU0d00KLS0tIGRkMy9hcW5QQXo2OHQvVU1HS3Ro
            NkE0R3ZENUYrSUkxb1lXUi9tOVQ3RjQKGCNd9HqRrlJ6tnKvawO0ZwKryQpM1ENV
            7RX/SgMYgNwOSFK3cR7B6XNWKpChqXEg5Knqr06/sDy/ui0pTeDwww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T21:37:29Z"
    mac: ENC[AES256_GCM,data:6BWA5PFlBCoqxmfojvGSxowlB4DWWPxtJkQssl6q/tWV1HED8OyAjcE0nlktV2j0eVmezM59UyMYK3al4ZrU3NA1eVJf+fGEiwXEGDsLgk3SwRiLtKvFpPI68UKCL5CgZebXHd0mKsD5Mnyv+ACwkmfXY4mxWM9uOciFgS7Yz6E=,iv:K7wg67qEHss6Gi5ERH3aoz4EeqLRgAg1Lqb2ZFqSGWA=,tag:pLWu94TNGNIEPnD98hpdxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
