apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
stringData:
    values.yaml: ENC[AES256_GCM,data:VQw1CyBeL+/EfvcKETC842HaE+m8G73iRB76Ovj+qK/Hmc1FmtOAE9QzlH6Gp86+GkWmQAoZBPWZAwrlsgWE299ejPUqqW5xhvDaNBYEqMiwHQv0Ye3+T3ZqJqdVfmtEjgqtVhIA81S+aF+RqsYYJa6t/9T7DV/LX2A=,iv:z9tRuNF5ETlHWTq2tNIFRebn9HI/6IqEGO5M26Um9sw=,tag:9Sbm4HSexg4uFiLYYRqVog==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbnNNQmh2MDhpajVpaVBI
            UGw5TVNiM2tXSFFXSTJBVmhJZW1jdEdxT1hvCjlocUFGSmJVaXVBRkxTM1JMeUVi
            eW5uWVBsUWhDWDRkNkJlOTgvWmt0SUkKLS0tIE92Y2RES1dzcWxRVEsrVkRhY2FB
            c2MrdklsZDBhcXloSVFEVGozcFZyWjQKQQ43TBTDW+y/+/LkXyuytqH8YuNZ1C+e
            +PRgfj6O3cmggDsx2/XhPEk2Y3TArEQl6TW/1XrHGzfERbo67s/rYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T21:37:07Z"
    mac: ENC[AES256_GCM,data:i9d3jRR2VAJWuVHAMYnzOZKiqEY9zRHgnViNJID/AEE2RelUNPEVesnV/t8ck2DYslUitJYBPfKJaWlWC8RgU8jL0vz1RFwKtur7BzwRtwj/zn9XeIEymyqacO898MMe7lGMgLVH3jXAGYCh9K6NvWCHUV03vnPJujPbNgrP6z4=,iv:Edwo8N67sVvA9cK0SJbHXScuQaRbdgwuDpcS4qkHARA=,tag:iDMOIWptRVWQwuwOHn3Lmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
