apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
stringData:
    values.yaml: ENC[AES256_GCM,data:vyUUM0FnG7mX7Of4UisR5Ngo9J+xzU363B2SBjbXxUAkhcNuTkyMrK8Cr9/tQc0PedgELkRsbkQEaV5MttRVJtlllbdNGoJ4zczyIL3ycKrKMs8d91QI1bZFmH3gg5U8atNtHkAAoNptTEbRiVfqI/PJV7uYrwxLbUfcCg0pXzlIVxOwNb+jaUXsrarMaAyFmCl70tQJL/TMq7AhMPYPMLLp12B/+aTl/zeM8MX04f/x58kkNzXsdc0hmA==,iv:CNSEtG+63Y0eomY+UyBAsBP4AxAI5szYzklbV/+8jts=,tag:7/IraJRMMj9qGx8PTqB82A==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc0dvZHVONGlodkRhZTB6
            QU1lcVFCMnd1NFJBWW50dUd4ZXJqUGM0V1ZrCjVGelhDZC8wdDlGdlhOSXdOU3hU
            VUFhYnV1WVpMNEN4cHp3RitiQlBZR3MKLS0tIDY2T0xZejJqc21zaldoU3ZON1lB
            bjgwb3RqcjdkZ3BzVzZCL0FvOGhwRDAKuYa8z7jmU5PLEIAYjAFGiohAonE+qfmn
            qjBrDrfBdVEAm2Yg77GI2f9eqmWfVKh5sXp5/ktqqMdu2zq4ZwbuTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T16:14:36Z"
    mac: ENC[AES256_GCM,data:CJqN5TRvFKiHj+SpU+rTGLsVXKgacP8c3Zyt+SuUjxMCfBDHWh+816t7vHNcfKT02AKmmddq//Nz1WutJE177hhiLUftEmuUd6S+obQJKB+RLMGwtsIeh64Z94wiNkD4yXcA2biwgZq/kak64a9SuaoilpqN9RkbQUF1xi7LmH4=,iv:IUeD2SchnAVhBWd03jwGEY+2vLy9KgvbViqdkPZftDQ=,tag:Z5JUfUZ5oN/GeIfhDS1PPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
