apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-nfs-storage-class
  nfs:
    path: /mnt/tank/k3s/grafana
    server: 10.40.10.10
