# monitoring/grafana/persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana-nfs-storage-class
  resources:
    requests:
      storage: 10Gi