---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/networkpolicies/baseline
  - ../../../../components/networkpolicies/gateway
  - ../../../../components/networkpolicies/all-namespace-egress
  - ../../../../components/networkpolicies/allow-internet
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml