all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    proxmox_nodes:
      hosts:
        asgard:
          ansible_host: 192.168.20.10
        midgard:
          ansible_host: 192.168.20.20
        muspelheim:
          ansible_host: 192.168.20.30
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    pi_nodes:
      hosts:
        raspberrypi:
          ansible_host: 192.168.1.110
      vars:
        ansible_user: pi
        ansible_ssh_private_key_file: ~/.ssh/rpi

    k3s_nodes:
      children:
        controlplane:
          hosts:
            k3s-master-1:
              ansible_host: 10.30.1.1
            k3s-master-2:
              ansible_host: 10.30.1.2
        workers:
          hosts:
            k3s-worker-1:
              ansible_host: 10.30.2.1
            k3s-worker-2:
              ansible_host: 10.30.2.2
            k3s-worker-3:
              ansible_host: 10.30.2.3


    # local_services_nodes:
    #   hosts:
    #     local-services-1:
    #       ansible_host: 10.30.72.169
    #     local-services-2:
    #       ansible_host: 10.30.54.112

    # kubernetes_master_nodes:
    #   hosts:
    #     kubernetes-master-1:
    #       ansible_host: 10.30.65.44

