all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    proxmox_nodes:
      hosts:
        asgard:
          ansible_host: 192.168.20.10
        midgard:
          ansible_host: 192.168.20.20
        muspelheim:
          ansible_host: 192.168.20.30
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    pi_nodes:
      hosts:
        raspberrypi:
          ansible_host: 192.168.1.110
      vars:
        ansible_user: pi
        ansible_ssh_private_key_file: ~/.ssh/rpi

    infra_nodes:
      hosts:
        infra-1:
          ansible_host: 10.30.34.55

    local_services_nodes:
      hosts:
        local-services-1:
          ansible_host: 10.30.72.169
        local-services-2:
          ansible_host: 10.30.54.112

    kubernetes_master_nodes:
      hosts:
        kubernetes-master-1:
          ansible_host: 10.30.65.44

    debian:
      children:
        infra_nodes:
        local_services_nodes:
        kubernetes_master_nodes:
      vars:
        ansible_user: slux
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519

