---

- hosts: debian
  become: true
  roles:
    - { role: debian_role, tags: ['debian_role'] }

- hosts: proxmox_nodes
  become: true
  roles:
    - { role: debian_role, tags: ['debian_role'] }
    - { role: proxmox_role, tags: ['proxmox_role'] }

- hosts: infra_nodes
  become: true
  roles:
    - { role: debian_role, tags: ['debian_role'] }
    - { role: infra_role, tags: ['infra_role'] }

