---
- hosts: proxmox_nodes
  roles:
    - { role: debian_role, tags: ['debian'] }
    - { role: proxmox_role, tags: ['proxmox'] }

- hosts: infra_nodes
  roles:
    - { role: debian_role, tags: ['debian'] }
    - { role: infra_role, tags: ['infra'] }

