# monitoring/prometheus/persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-nfs-storage-class
  nfs:
    path: /mnt/tank/k3s/prometheus
    server: 10.40.10.10