apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: authentik-db
spec:
  database: authentik
  dropOnDelete: false
  masterRole: authentik-role
  schemas:
    - public
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: authentik-user
spec:
  role: authentik-role
  database: authentik-db
  secretName: authentik-db-secret
  privileges: OWNER
  secretTemplate:
    PQ_URL: "host={{.Host}} user={{.Role}} password={{.Password}} dbname={{.Database}}"
