apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/networkpolicies/baseline
  - ../../../../components/networkpolicies/internal
  - ../../../../components/networkpolicies/allow-internet
resources:
  - ocirepository.yaml
  - external-secret.yaml
  - storage.yaml
  - helmrelease.yaml