apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/networkpolicies/baseline
resources:
  - ocirepository.yaml
  - external-secret.yaml
  - storage.yaml
  - helmrelease.yaml