apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-operator-secrets
    namespace: ext-postgres-operator
stringData:
    values.yaml: ENC[AES256_GCM,data:9/Ohcfc7+6AX+rcrTmdBbV1BRaSCHPyxtcubM7wyIrstG/dflZuLBmqEQAfBU1VoeLX9iPE1ohm405GGxNnI6acfY0wV1GWQoWGZV9Y1X6IROsAn5el23VxGfEP5Tyj2eKzLQJrYkkqXQKre,iv:o7/TI64z8Napd91VYTpzlKWJsTtFwltANTm3FtKHIuU=,tag:Y/wtUfcej/JO3VxbW0AFRw==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmdIWEVoSERwckhuWHRO
            T0ZaU2NDcTNEcnB1QjBVVURKd29xaHNkbDJzCnhuYnJkZzVzNkFjY1JINE14WTRv
            VXdhbFhLdExKcjdZem5mbHFveFJWVDgKLS0tIEV3OWc0S3BjV2lvdzRpdllSUGZ3
            Z3lNRTNRdjNEbUMyTGNzY3pHYnhxZFkKHOcBxIndgE0XUMlBOz/7H98Mjz1VC9jg
            Ko25rvgGVP+gb3Ecwlv89+AtkqPqzoanvqf3v4B+Z9hlYZmw1lt9uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T15:25:35Z"
    mac: ENC[AES256_GCM,data:jadjqxn2V+9yzc+ZNN8eB2wxibxG7GfXir/iWbcMqY7XNahRukZCIHotOWjVhh0WmJBZ2jF6O6sKN3b319M8IEdxf1Rh2Rf+50X0Gdu/x7ezj1lX9yKKgBQX8saY9d1jQJ8mqDHs5HeVe3V6IoUs0/YzRv2sjfRWD+9/cwK/WiM=,iv:AV0MKfTbw4k8IPCaF3WCUW2kL2kQIvHmjA4NkIWzxJ8=,tag:SdE85N7ogMtkJQXoUi9dEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
