apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-operator
    namespace: ext-postgres-operator
stringData:
    values.yaml: ENC[AES256_GCM,data:qW/gsHd/lPkCmYUIwa7LPavqHkNLunmITY4/B+MDPZ/5Q4wHtMHGqHFD85/xN7z0G49PTYDAsqjYWvnCaPxq0Kj3eU2yGTpfADZGiNLdtsaS0zeGyr6AVN6IKndLZcvjEZQTznNfDS7620kKF1IDpojoIqoidsXCyvgLVmiwm/rUB7yUhHmF4WLz,iv:uJZU1E66SIwsUuCOaO+oJ5jF1XI1uGVZdI38XXwjjo8=,tag:DKq+OI7RMWyyDtWnJB2bUg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQk9Wazh3bFM4djkvcDB2
            eURQejl2TVpjMzZxdDBad0VJdktYdkFldkNvCkN3bERleXViVFJlREUvcVU0bkJk
            U2dDNERnaEVHOEpERnBJQzR1OWVicW8KLS0tIHQrREtnWnB4ZmkzMWkxTkx6a3VJ
            M2dtVWVMM0o1REs3REpVcDBMWUJLOG8KjSLSx1/L3kXLOTsc116B6yCYcS4mqBmX
            l9ig+sHXEmmwPvs3rirMEAzGG17LlHx5D3PFa4z4BiLNfE6b3PMmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T16:08:20Z"
    mac: ENC[AES256_GCM,data:UBYprg7iS70xnSqhsWOrmVBQAKPbnBFMNXsA9Kou5VwkXF5C7u7FvvkHnteGdpfxQPqMK1kOeOTW5AYH3rnUKMuZsgqoD1mB2sfIcwtbwvpzrSiuRKy1kPUSnFSWQFFgXWeeChRRHOFiu/Oodh2CaNsKyKxw+jiYiOcrfuxbgm0=,iv:A3GVgC9DXN48tYhhztb+hEiJ2fI6F7s9yvYI5mcfjJE=,tag:rSKa8plM3m2R0RIPMm5CGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
