apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-operator-secrets
    namespace: ext-postgres-operator
stringData:
    values.yaml: ENC[AES256_GCM,data:Ygyj+iYblNMm3YVquHkupKjvtwDYMc2l4gNnCUnT6vX4bPc9tFWM4YNWiGRrYMly31PxZ/rhhGminajuyTsqbnBjUcv6jn7KHbIhCh1B/h0VJOTmnoZcodoBvtcr5M+QJY4jRYoxHvnHxm0R3uUhwc8SDpI8iih83kRvfos7MGmUutFLcIiIpq9k,iv:lC+hGLFSltTtwOI3vwP4cw4z74k+ZS9gH114YSdcOdA=,tag:bDcwVo68RYEaGafFn0Wx5g==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN2hPWmdsRDUrVDFJNWwv
            TVJORlhBZHdpSDZTc0dOUUZmdWhPK1ErbXlnCkcyUk5SdkxoUHk5RlczeTdwbW4w
            Smpmb3RBNWMwVnJlT3R0TXZZZml1dDQKLS0tIEtpR0dHc21YRDJ5SFltTDZnQysz
            dkVtOXU5ejlXMFdQWks5RWpGSTR1MUkKSWSf/MgyJEgbhYfwrSIwX5AvZ31cA/Er
            ZXaTRO2VR88X6dlLfs0XbLow91ODO6nstXo+36/9UFOftJaZy8doIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T15:59:27Z"
    mac: ENC[AES256_GCM,data:l0yJUhdIrzlJra0/1lnAbqnh6ZbFmUsExG7zJAH7LIkOITqYrUQR5L1hs17RkdS1LhKwpTFLWh3m/hwdK/Azg6n3juEcfjCEB4FolBqvVCPb3yRizU90Hhxi45XVHbte9m+uS2NSoHcE6AYnvLYujXkiqG0jnv0cK9jQ8CuN2mE=,iv:NHRn/hE6BJ9Ce66XQ8xWiQDKMkXEopp/vmgal6/yoSI=,tag:N3yGHjbJcEFVYBbDN/IvlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
