apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-allow-internal-gateway-access
  namespace: envoy-gateway
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: internal
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443