apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deny-all.yaml
  - allow-ingress-internal-ip.yaml
  - allow-ingress-external-ip.yaml
  - allow-egress-except-system-namespaces.yaml
  - deny-all.yaml
  - allow-egress-pod-kube-dns.yaml
  - allow-ingress-ns-observability.yaml