apiVersion: v1
kind: Secret
metadata:
    name: pushover-secret
stringData:
    ALERTMANAGER_PUSOVER_TOKEN: ENC[AES256_GCM,data:6k0p3h/VyN6fk7yF89562YhqmfJeutyh3rjL9wKB,iv:xwRPIV8t/iLWFScecRFfYaacmKP1jJi8UXPX/DZoiWA=,tag:4At1hv7yIwWZ0SBRL+4wLQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:te0M10MLYaiD+b41nQpHaKgMYA4ZUFk+eQu5qjLn,iv:ijgRRkXESSusYlDctkdYuQQ46lJRMleFkiyCNYJjC1M=,tag:XY9TC2yiy4mTSPvCzbwQYA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdWZ2VkZFV01DeVlLcnpi
            RUIrdWQrSUp4NDdQTDV0RXFDZkZ1MXJWbHhZCndsWmZsRm10YWxqSDJjRFV3ckVx
            RFpSWnBaSkMxUzA3OWdUTGpzekdMeE0KLS0tIG12K3dJRVl6eHVpY0g4SllHVDRU
            Z0d3Z09qTW9JVXdtWkh1cGlIbVo4dTQKrMFD+c4qN9wna3Tvh9EDs+xUfC7768CK
            WZFU+3o4/NnfPwGauix3974Nl0TG5r8r4JXZemjQrQhsgMn6vbV2gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T08:23:19Z"
    mac: ENC[AES256_GCM,data:LK3WVROhchfb0DSQ4EWSdxYWoQgsaw6Lgs95/Fq54HZdvQuWyUpVFApxJSB+xy3yWmA8VH9G7aRpsovxXcAIj4dpgCMaLQZQR8gkjDlrXvyZ4lfR1Rrme24GwJKm5deJsZi1yV/tGGEm3uiQX3oqsR+y7RKFdk4tqm+H4pio+MY=,iv:4BJMXQ8ZdnC2EZiQhvT5p348POdH8yLDDOtob7nslnQ=,tag:kOgApN83EfOtkrULPlKKGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
