apiVersion: v1
kind: Secret
metadata:
    name: pushover-secret
stringData:
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:idCYuQCoDrnJkrUEmHn/+wmj1/J1E8fDr5QNVPil,iv:GHc7zWu2DMjhYW36uKvkiTWGEGOgEP6FzqbEII5kg6k=,tag:XURouf7ShOPjhpdxq5i1zg==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:te0M10MLYaiD+b41nQpHaKgMYA4ZUFk+eQu5qjLn,iv:ijgRRkXESSusYlDctkdYuQQ46lJRMleFkiyCNYJjC1M=,tag:XY9TC2yiy4mTSPvCzbwQYA==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdWZ2VkZFV01DeVlLcnpi
            RUIrdWQrSUp4NDdQTDV0RXFDZkZ1MXJWbHhZCndsWmZsRm10YWxqSDJjRFV3ckVx
            RFpSWnBaSkMxUzA3OWdUTGpzekdMeE0KLS0tIG12K3dJRVl6eHVpY0g4SllHVDRU
            Z0d3Z09qTW9JVXdtWkh1cGlIbVo4dTQKrMFD+c4qN9wna3Tvh9EDs+xUfC7768CK
            WZFU+3o4/NnfPwGauix3974Nl0TG5r8r4JXZemjQrQhsgMn6vbV2gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T09:34:21Z"
    mac: ENC[AES256_GCM,data:gnlpaLnb0TihMBdZi9hFFXLmC+z+1SyOVcH6k3Mo6IwovGsyLsaSbM+LiQ6aajwg3A1fe32K07I2WH3NYcacmHuBmhoXt2Wi8gzZdtnHeTviEwX0nbHspdtwyHdEZn5BtfQer6q2H+Mb0OLYirATjBS7mI1cOsfZh2k+GwTDG00=,iv:iR/6/Xbuj1K84gL9E4vebzrDzgMKNy9aYbSyDQDaan8=,tag:BAfoBQ8noMAO8fo2sqId1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
