groups:
  - name: system-health.rules
    rules:
      - alert: InstanceDown
        expr: up{job="node_exporter"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.hostname }} is down"
          
      - alert: HighCPUUsage
        expr: 100 - (avg by(hostname) (rate(node_cpu_seconds_total{job="node_exporter", mode="idle"}[5m])) * 100) > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.hostname }} CPU saturation"