---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        POSTGRES_URI_ARGS: "{{ .POSTGRES_URI_ARGS }}"
        POSTGRES_DEFAULT_DATABASE: "{{ .POSTGRES_DEFAULT_DATABASE }}"
  dataFrom:
    - extract:
        key: ext-postgres-operator