apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-operator
stringData:
    values.yaml: ENC[AES256_GCM,data:4uYkJ83kbzyOPX+x9iAkhuQvnUoj0j1V1X9tfGpTVGh/Z7/jYup3hME3EIzyFHVgG07IpglT71gC92UpgHz0GRPZRORxo5MsNY/bEHNEBge653TbOW/oTozqDbFRu9ffwxnH8fNloJ5AEKRylwDpSpMQo3NpDl69MU/E0nO1WPt5Y+izU2KxLg==,iv:gZDo5658aLQKbm/t1gAEM6ZTUS3wsJj/db6SlMhhggA=,tag:e9mupgObGBN4LNhDYHAlzw==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTkRQUFFsZ0xDbGNQYmJz
            ekxhaFBEZ2hlQ25yeHZJR2J1ZVlxa2h5ZEZRCktCV3l3U2Z0U2poR21iajQyYUR4
            VnBaaTlYdmJ3ZmQwaDdGRGo2cFdodncKLS0tIExpNjVHbk5hYVB5YmN4Z2wwY1FG
            cVNRMCszejRwaXQ3WWVRK0p6R2dsSTgKr6XzUfBgV5QolPCY94INlQ+C54DN8oZL
            EkM6rwPAAI8w2PsI8+nK//gEBxa1fH6J05YHtnvhpeKzhZDVtb9b2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T20:08:12Z"
    mac: ENC[AES256_GCM,data:/4AEGZblJy1Owy/q311Db4Aw8uMY835ANdDGPUzhd668tED+es7S+rqs8FV2RI31Fkn5ohtug7LgWyZn+ITgodJCZJ8DlfxkQ7jfqlDFwptxxwj/jI+FE8bE+tfKSSqDQcIYSewfi9s7nsKw7ETxF/TSPidoqwerVMAsLv2exIc=,iv:OAtvBL2WMAi97FPwHaDyZmalUiOtM0FmqsDzwPIv7+s=,tag:UhzjVp7x0xo6nlxQkkK2mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
