---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chartRef:
    kind: OCIRepository
    name: nextcloud
  interval: 30m
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_USER
        passwordKey: NEXTCLOUD_PASSWORD
      host: next.{DOMAIN_01}
      mail:
        enabled: false
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'check_data_directory_permissions' => false,
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'mail_smtpmode' => 'null',
            'skeletondirectory' => '',
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.42.0.0/16',
            ),
          ); ?>
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NL',
            'maintenance_window_start' => 2,
          ); ?>
    
    # Route
    httpRoute:
      enabled: true
      hostnames:
        - "next.${DOMAIN_01}"
      parentRefs:
        - name: internal
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
          filters:
            - type: ResponseHeaderModifier
              responseHeaderModifier:
                add:
                  - name: strict-transport-security
                    value: max-age=31536000
    
    # Storage
    persistence:
      enabled: true
      existingClaim: nextcloud

    # Cache
    redis:
      enabled: false

    externalRedis:
      enabled: true
      host: ${NAS_IP}
      port: "6379"
      ## Use a existing secret
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        passwordKey: REDIS_PASSWORD

    # Database
    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: postgres-secret-nextcloud
        usernameKey: ROLE
        passwordKey: PASSWORD
        hostKey: HOSTNAME
        databaseKey: DATABASE_NAME

    startupProbe:
      enabled: false
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 60
      successThreshold: 1

    livenessProbe:
      enabled: false
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      enabled: false
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    securityContext:
      fsGroupChangePolicy: OnRootMismatch