---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  chartRef:
    kind: OCIRepository
    name: nextcloud
  interval: 30m
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true
    nextcloud:
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: ${NAS_IP}
        - name: REDIS_HOST_PORT
          value: "6379"
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: NEXTCLOUD_USER
        passwordKey: NEXTCLOUD_PASSWORD
      host: next.${DOMAIN_01}
      mail:
        enabled: false
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      defaultConfigs:
        redis.config.php: false
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_domains' =>
              [
                'nextcloud',
                'nextcloud.selfhosted.svc',
                'next.${DOMAIN_01}'
              ],
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.42.0.0/16',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'default_phone_region' => 'NL',
            'overwrite.cli.url' => 'https://next.${DOMAIN_01}',
            'overwriteprotocol' => 'https',
            'quota_include_external_storage' => 'false',
            'check_data_directory_permissions' => false,
            'skeletondirectory' => '',
            'knowledgebaseenabled' => 'false',
            'maintenance_window_start' => '1',
            'enable_previews' => false,
            'trashbin_retention_obligation' => 'auto, 30',
            'auth.bruteforce.protection.enabled' => true,
          );
        redis.config.php: |-
          <?php
          $CONFIG = array(
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => getenv('REDIS_HOST'),
              'port' => getenv('REDIS_HOST_PORT') ?: 6379,
            ),
          ); ?>
    
    # Route
    httpRoute:
      enabled: true
      hostnames:
        - "next.${DOMAIN_01}"
      parentRefs:
        - name: internal
          namespace: envoy-gateway
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
          filters:
            - type: ResponseHeaderModifier
              responseHeaderModifier:
                add:
                  - name: strict-transport-security
                    value: max-age=31536000
    
    # Storage
    persistence:
      enabled: true
      existingClaim: nextcloud
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
        accessMode: ReadWriteMany
    # Database
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: postgres-secret-nextcloud
        usernameKey: ROLE
        passwordKey: PASSWORD
        hostKey: HOSTNAME
        databaseKey: DATABASE_NAME

    startupProbe:
      enabled: false
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 60
      successThreshold: 1

    livenessProbe:
      enabled: false
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      enabled: false
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: nextcloud
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: nextcloud
              spec:
                template:
                  spec:
                    hostUsers: false