---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: &app nextcloud
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: *app
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: homepage