---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: ${NAS_IP}
    path: /mnt/apps/nextcloud
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  storageClassName: "k8s-nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi