apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: ${NAS_IP}
    path: /mnt/tank/nextcloud-data
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  volumeName: nextcloud-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: ${NAS_IP}
    path: /mnt/apps/nextcloud
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: nextcloud

