---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pocket-id
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: pocket-id
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: selfhosted
