apiVersion: v1
kind: Secret
metadata:
    name: pocket-id
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:h7MWFup7rrlpQ0OueeK+jZANU92vkCuc0XU7m6noYbqrhWQpHpxc1Q0fgUg=,iv:zxtpQ/kTGhUFitJKW2AgPkclbu4UiT32XMhBFa2Xsn8=,tag:zcMeXWDxfFZsda/8QzvwdQ==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZFRTV2Z5bkw4cUZnajQ5
            SUNVZG5vNm5IWWRzTE1saXU4ZlIrUElFT0VvClVQRm5HY2M5Ti9UM3Rhbnd5VWMz
            UkJqOEpNZkhWSlhaSmNweVRuUnVuUTQKLS0tIGFaSjZuZFkxTzV1aUhNOWJUSENs
            UGdGU01SWkdIUktjNzFoa2tTZEg3bVkKxUksR98J+kPRj+46ePTY6vrzcxjOH6of
            1xcUahAiZ6aSy6tzZRt3b1E6hOtf4eFyfOXJB9wlTbrgOexpIPyLHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T21:48:55Z"
    mac: ENC[AES256_GCM,data:VMhh3cOAyhu5rVd8zQL0ptFrwFgAVjWJWpDc+W+TJ2jybGys1rOU4XOzMvSHjDeFi/Ja2lG3g8gMB+GtSOg9a5kUnkefUlk5Ggwv9EtqZKHea4cwdbxh8QgxyVp62JWfH5R9uoS7+1dyZxMsMUVYAlPsNbZISV94Q9S1SkAIORU=,iv:lPKYceBmmxXv/ghOI1PTwmqQkLOSj3uKWh3E6dYr6os=,tag:nq1jvN0BU+lLYEWJOW5BUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
