---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-id-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: ${NAS_IP}
    path: /mnt/tank/security/pocket-id
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-config
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pocket-id-config

