apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.x"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
  interval: 10m
  values:
    csiDriver:
      name: "nfs"
    storageClasses:
    - name: nfs
      defaultClass: true
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 10.40.10.10
          port: 80
          apiKey:
            valueFrom:
              secretKeyRef:
                name: democratic-csi
                key: apiKey
          allowInsecure: true
        zfs:
          datasetParentName: tank/k3s-nfs
          detachedSnapshotsDatasetParentName: tank/k3s-nfs-snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0750"
          datasetPermissionsUser: 1000
          datasetPermissionsGroup: 1000
          datasetProperties:
          "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
        nfs:
          shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: 10.40.10.10
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: [10.30.0.0/16]
          shareMaprootUser: 1000
          shareMaprootGroup: 1000
          shareMapallUser: ""
          shareMapallGroup: ""
    controller:
      driver:
        image:
          tag: next
  valuesFrom:
    - kind: Secret
      name: democratic-csi   # the SOPS-decrypted Secret
      valuesKey: apiKey      # key inside the Secret
      targetPath: driver.config.httpConnection.apiKey