apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi
    namespace: democratic-csi
stringData:
    apiKey: ENC[AES256_GCM,data:XFK61CrgUpoE3yc5pmkFPYg0nhySyLA6B3pVdaRJZ8V3dlJYhwXRcqB4n/dUGhiVeNlamUkFBumM9q4RmoBzVis4,iv:h2S2LWucF+8HrUyV/kHxvpimE8hE9OHnTnASQa3geUY=,tag:EDMYg/V3kunqtxBJ8f7vIg==,type:str]
sops:
    age:
        - recipient: age1e37dddpcd83kdc45xsle36a9dxc492t0xnpsakyk7478zlga5agsrqjdad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdU45TE5jM2JaMTE5bHR1
            ZDFhUXFhd01aNSs3N3lEbGhlZmx5ejVYbUJnCk4rQThxTjNMdkc2UnJRR295NDFn
            SFVSSHFRRHM2OUxLY2tFVWZJeE44eWMKLS0tIHI0cmVjaEkvMytZVnFyNVNGdzZQ
            cWtzWmhmMFZGSmw1eURVNmplWlRST00KUP0hLWoYT5cMRMzeFrHS0cers9uw32S8
            1/tzRGp2cTRncIVgFBbZoV0xUeG6iV0+plIcQP+tm3pOqAcyIyD8fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T18:47:12Z"
    mac: ENC[AES256_GCM,data:+OAuDWx3+4/jeQj2pX8L+DxqmCZ6pLLTDqKoLFxIJKebwmsncpDp7FLXBeJ4LzcfSjWefCfgHst75ky6PNXl2K5YxdyCLQCi5pCTVMnCMmuBHXqA8c5/JgmtS5RyPwPHsKqD69QX8NJMa87O8+FgaD3TmuNsM6VxtLMq50wcx80=,iv:bwUgBcNy5RubmHGewUxq+SCgQUPTHI56nv6wR6+8ZVs=,tag:6ybmkntT7R+x+T+mVWWMxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
