apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi
    namespace: democratic-csi
stringData:
    apiKey: ENC[AES256_GCM,data:vDEjNrQqCAj28sWhN+SDBMlKtNbSyrEgdP9LgW1Kv9OSJD7WtkE6zhjRGweWZ38VyPKsUwDWBvja51vi46pY5e26,iv:s/KkPKztO9uymR5t+0AEeLok8eEfxFdNKMV5lCm+cys=,tag:/DUJvU+byDfQm8j6t/k8ig==,type:str]
sops:
    lastmodified: "2025-10-07T20:58:31Z"
    mac: ENC[AES256_GCM,data:mNm5deBWYSxg09qC/YHrVSYZIkt4u2oUAbGL09po3s8BzUCXAtoRpfHLiKB8sD3pX7EhFtqSugRoHLBptuS0qjT7EwRB4QBHwcGWZNLOHwA9m7l/sA2Nc5AFFc/z0EcG/OBgMlE6Vnd5oisn/FO+YN2yc+NocS0aGioHSy1QgBw=,iv:h2oeObVczBW9cN/kDG7CAdAvMfPPchKJNnFSC3+NXCo=,tag:C1TVXYITVzcI4Oi7CZeEuw==,type:str]
    pgp:
        - created_at: "2025-10-07T20:58:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5bcOv4VpS+jAQ//WlGLnzSToTC1BqdpszUcDxR99tB+6SOP+gDgS/0a853l
            dtnxOfirxJO94kRqtr3jrlwOSiJFJ0ZVs8Qqo9zlj+sJn1ymcGMWK8oFmV8K3qaF
            vQy9G6bI86CfmjFLWNzEDdTbdoKmVPJ471xdoV9iTxqp8lPWUk6dfvuPU6BWSxO2
            27mI6tZsb3zf3COMQQsV/FgLDxyG3TQxR/Ju+nuUqk/r+S+zex52/tT2y3wa3Qp/
            72+MKbde6l9whtoFVj5OjhHjU/kazVg6Ti/Cox34bKbXeRP5guzvZRvYppGU7eKj
            ljkNZgl+rF1OzHhAyFPcJHhfhyxawuL8E5mmPvdkDFT8ed7WbSNByIcJHAB7VbpU
            XJa/4OEXyMNM9U2O8M0Zr0W2UM/HldFGSUizcC4mN33i/eHObUkdTl/gpn5grFcE
            362OkUHP85W9LgM9sep3MuDV+gzkRTpVckgtreZQTuq60SmkrMivOcDg/iRE1xyb
            VPNoONxvfn7GWGw0/2kuwBDNW/qb34oakgVvwjmmO54rnpdR0US4V+AhiHo6Wwh7
            6tKoMiqBZuku3PNMjka2a2+rGOIYhGYvWG36tZAHMbHlw5+v3gqSzh065KTZhlif
            KhewW6UJ21yi2EUdU/VuZBWMTDZTcdw+soIbQltmpNpuRHI7EeO3IW6nI1IKcqLS
            XgEY6vl+1aIIyopgbm+MBWWgNGXdIKnxTjP3e8WCF1MhP3nTM6wEIK+mxfsd499l
            NkGEv7FPCaYmpaabkkK8rCr+avGedizEGC6PeqNvwUrGWajgvlOyRfq/wzJ3mMo=
            =pGd8
            -----END PGP MESSAGE-----
          fp: 710CA0F145A7191773CF2271C78D486F05CCD667
    encrypted_regex: ^(stringData|data)$
    version: 3.11.0
