apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-bgp-cluster-config.yaml
  - cilium-bgp-peer-config.yaml
  - lb-advertisement.yaml
  - lb-pool.yaml
  # - clusterpolicies.yaml